# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Application module.
Contains functions and classes for working with general parameters of the application.
"""

from sys import version_info as _swig_python_version_info
import _app

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _app.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _app.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _app.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _app.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err

def _GetVersionInfo():
    r"""_GetVersionInfo() -> CYMString"""
    return _app._GetVersionInfo()

def ActivateRefresh(Activate):
    r"""
    Activates or deactivates the refresh of the GUI. Use this function when extensive operations are performed on the network, and you want to avoid any flickering or to minimize the overhead caused by the refresh of CYME mainframe.

    Module: cympy.app

    Remarks:
       - It is recommended to always call ActivateRefresh(True) in the finally clause of a try..except..finally block. This way, if an exception occurs, the refresh of the GUI will always be reactivated. In embedded mode, if the refresh is not manually reactivated, some post-process is done to ensure that CYME stays in a stable state, but it is still recommended do to it manually.
       - When ActivateModifications is set to False, the refresh cannot be deactivated.
       - When running scripts in stand-alone mode, this function does nothing.

    Args:
       Activate -> bool

    Return type: 
       None


    """
    return _app.ActivateRefresh(Activate)

def SetValueInitialization(SectionName, Key, Value):
    r"""
    Sets a CYME INI file value.

    Module: cympy.app

    Args:
       SectionName -> str

       Key -> str

       Value -> str

    Return type: 
       str


    """
    return _app.SetValueInitialization(SectionName, Key, Value)

def Print():
    r"""
    Displays the Print Properties window. User can then print current network to the default printer.

    Module: cympy.app

    Args:
       None

    Return type: 
       None


    """
    return _app.Print()

def ShowMessage(*args):
    r"""
    Displays text in a message box as a pop-up window.

    Module: cympy.app

    Remarks:
       - This functionality works both in embedded and stand-alone modes.

    Args:
       Message -> str

       Caption -> str (Optional, default: '')

    Return type: 
       None


    """
    return _app.ShowMessage(*args)

def GetMessages(*args):
    r"""
    Returns the messages encountered during the execution of the last command processed by CYME.

    Module: cympy.app

    Args:
       Severity -> cympy.enums.Severity (Optional, default: cympy.enums.Severity.All)

    Return type: 
       list of cympy.app.Message


    """
    return _app.GetMessages(*args)

def CreateMessage(*args):
    r"""
    Creates a message that can be reported to CYME.

    Module: cympy.app

    Args:
       Text -> str

       Details -> list of cympy.app.Message (Optional, default: [])

       Localizations -> list of cympy.app.Localization (Optional, default: [])

       Severity -> cympy.enums.Severity (Optional, default: cympy.enums.Severity.Error)

    Return type: 
       cympy.app.Message


    """
    return _app.CreateMessage(*args)

def CreateLocalization(*args):
    r"""
    Creates a localization that can be used to create a CYME message.

    Module: cympy.app

    Args:
       LocalizationType -> cympy.enums.CymeType

       LocalizationValue -> str

       IsLink -> bool

       DeviceType -> cympy.enums.DeviceType (Optional, default: cympy.enums.DeviceType.Unknown)

       InstrumentType -> cympy.enums.InstrumentType (Optional, default: cympy.enums.InstrumentType.Unknown)

       EquipmentType -> cympy.enums.EquipmentType (Optional, default: cympy.enums.EquipmentType.Unknown)

    Return type: 
       cympy.app.Localization


    """
    return _app.CreateLocalization(*args)

def ReportMessages(*args):
    r"""
    Reports a message to CYME.

    Module: cympy.app

    Args:
       Messages -> list of cympy.app.Message

       eMessageCategory -> cympy.enums.MessageCategory (Optional, default: cympy.enums.MessageCategory.Python)

       ClearMessages -> bool (Optional, default: True)

    Return type: 
       None


    """
    return _app.ReportMessages(*args)

def ToggleAbnormalConditions():
    r"""
    Toggles abnormal conditions display.

    Module: cympy.app

    Remarks:
       - This function has the same behavior as the 'Show Abnormal Conditions' button in CYME Simulation toolbar.

    Args:
       None

    Return type: 
       None


    """
    return _app.ToggleAbnormalConditions()

def GetKeyword(KeywordID):
    r"""
    Returns a keyword object by its name.

    Module: cympy.app

    Args:
       KeywordID -> str

    Return type: 
       cympy.app.Keyword


    """
    return _app.GetKeyword(KeywordID)

def ListKeywords():
    r"""
    Gets a list of all keyword defined in CYME.

    Module: cympy.app

    Args:
       None

    Return type: 
       list of cympy.app.Keyword


    """
    return _app.ListKeywords()

def ExportActiveView(Path, Format):
    r"""
    Exports the active view to the specified image file format.

    Module: cympy.app

    Args:
       Path -> str

       Format -> cympy.enums.ImageFormat

    Return type: 
       None


    """
    return _app.ExportActiveView(Path, Format)

def GetInputParameterAsText(VariableName):
    r"""
    Gets the specified input parameter as text.

    Module: cympy.app

    Args:
       VariableName -> str

    Return type: 
       str


    """
    return _app.GetInputParameterAsText(VariableName)

def GetInputParameterType(VariableName):
    r"""
    Gets the type of the specified input parameter.

    Module: cympy.app

    Args:
       VariableName -> str

    Return type: 
       cympy.enums.ParameterType


    """
    return _app.GetInputParameterType(VariableName)

def GetParameterAsText(VariableName):
    r"""
    Gets the specified parameter as text.

    Module: cympy.app

    Args:
       VariableName -> str

    Return type: 
       str


    """
    return _app.GetParameterAsText(VariableName)

def ListMultiprocessingProviders():
    r"""
    Lists all the multiprocessing providers.

    Module: cympy.app

    Args:
       None

    Return type: 
       list of cympy.app.MultiprocessingProvider


    """
    return _app.ListMultiprocessingProviders()

def ListMultiprocessingRequests(*args):
    r"""
    Lists all the multiprocessing requests.

    Module: cympy.app

    Args:
       userName -> str (Optional, default: '')

    Return type: 
       list of cympy.app.MultiprocessingRequest


    """
    return _app.ListMultiprocessingRequests(*args)

def GetLastMultiprocessingRequest(*args):
    r"""
    Gets the last multiprocessing request that was started byt the current process.

    Module: cympy.app

    Args:
       userName -> str (Optional, default: '')

    Return type: 
       cympy.app.MultiprocessingRequest


    """
    return _app.GetLastMultiprocessingRequest(*args)

def LoadMultiprocessingResult(RequestID):
    r"""
    Prepares a previously obtained multiprocessing result.

    Module: cympy.app

    Args:
       RequestID -> str

    Return type: 
       None


    """
    return _app.LoadMultiprocessingResult(RequestID)

def GetCurrentReports():
    r"""
    Retrieve reports that are currently visible in the application.

    Module: cympy.app

    Args:
       None

    Return type: 
       list of AppReport


    """
    return _app.GetCurrentReports()

def CloseReport(ReportName):
    r"""
    Close a report in the application.

    Module: cympy.app

    Args:
       ReportName -> str

    Return type: 
       None


    """
    return _app.CloseReport(ReportName)

def CloseAllReports():
    r"""
    Close all visible reports in the application.

    Module: cympy.app

    Args:
       None

    Return type: 
       None


    """
    return _app.CloseAllReports()

def RunXML(*args):
    r"""
    Executes an XML request in CYME.

    Module: cympy.app

    Args:
       XMLRequest -> str

       RequestOptions -> list of cympy.enums.APIRequestOption (Optional, default: [])

    Return type: 
       cympy.app.XMLResponse


    """
    return _app.RunXML(*args)

def ActivateOutputRedirection(Activate):
    r"""
    Activates / disables the output redirection used by Cyme.

    Module: cympy.app

    Remarks:
       - Only use this if you really know what you are doing.

    Args:
       Activate -> bool

    Return type: 
       None


    """
    return _app.ActivateOutputRedirection(Activate)

def GetExecutionParameter(arg1):
    r"""
    Gets an execution parameter.

    Module: cympy.app

    Remarks:
       - If the parameter has not been set, the function return an empty value.

    Args:
       Parameter -> str

    Return type: 
       str | None


    """
    return _app.GetExecutionParameter(arg1)
class _EnvironmentSettings(object):
    r"""
    CYME Python Environment Settings. Environment settings are general parameters that set up basic global characteristics of CYME. They differ from other CymPy tools in that they are not stored in modules, but rather in a public object accessible at the package level.


    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""
        Initializes self.


        """
        _app._EnvironmentSettings_swiginit(self, _app.new__EnvironmentSettings())
    __swig_destroy__ = _app.delete__EnvironmentSettings

    def __get_sou(self):
        r"""
        Gets or sets the system units (metric or imperial).


        """
        return _app._EnvironmentSettings___get_sou(self)

    def __set_sou(self, Value):
        return _app._EnvironmentSettings___set_sou(self, Value)

    def __get_lou(self):
        r"""
        Gets or sets the the basic unit for expressing length.


        """
        return _app._EnvironmentSettings___get_lou(self)

    def __set_lou(self, Value):
        return _app._EnvironmentSettings___set_lou(self, Value)

    def __get_sf(self):
        r"""
        Gets or sets the fundamental network frequency.


        """
        return _app._EnvironmentSettings___get_sf(self)

    def __set_sf(self, Value):
        return _app._EnvironmentSettings___set_sf(self, Value)

    def __get_bpacmva(self):
        r"""
        Gets or sets the base for the per-unit impedance of the Substation Equivalent.


        """
        return _app._EnvironmentSettings___get_bpacmva(self)

    def __set_bpacmva(self, Value):
        return _app._EnvironmentSettings___set_bpacmva(self, Value)

    def __get_bpdckw(self):
        r"""
        Gets or sets the per-unit Thevenin impedance that can be requested in the Short-circuit report.


        """
        return _app._EnvironmentSettings___get_bpdckw(self)

    def __set_bpdckw(self, Value):
        return _app._EnvironmentSettings___set_bpdckw(self, Value)

    def __get_bv(self):
        r"""
        Gets or sets the voltage to which the base voltage results will refer to.


        """
        return _app._EnvironmentSettings___get_bv(self)

    def __set_bv(self, Value):
        return _app._EnvironmentSettings___set_bv(self, Value)

    def __get_ot(self):
        r"""
        Gets or sets the temperature setting for temperature-controlled capacitor.


        """
        return _app._EnvironmentSettings___get_ot(self)

    def __set_ot(self, Value):
        return _app._EnvironmentSettings___set_ot(self, Value)

    def __get_aer(self):
        r"""
        Gets or sets average the average earth resistivity.


        """
        return _app._EnvironmentSettings___get_aer(self)

    def __set_aer(self, Value):
        return _app._EnvironmentSettings___set_aer(self, Value)

    def __get_cr(self):
        r"""
        Gets or sets the conductor resistance.


        """
        return _app._EnvironmentSettings___get_cr(self)

    def __set_cr(self, Value):
        return _app._EnvironmentSettings___set_cr(self, Value)

    def __get_emb(self):
        r"""
        Gets a value indicating whether CymPy is used in embedded mode.


        """
        return _app._EnvironmentSettings___get_emb(self)

    def __set_emb(self, Value):
        return _app._EnvironmentSettings___set_emb(self, Value)

    def __get_batch(self):
        r"""
        Gets or sets batch mode.


        """
        return _app._EnvironmentSettings___get_batch(self)

    def __set_batch(self, Value):
        return _app._EnvironmentSettings___set_batch(self, Value)

    def __get_som(self):
        r"""
        Gets or sets the section orientation mode.


        """
        return _app._EnvironmentSettings___get_som(self)

    def __set_som(self, Value):
        return _app._EnvironmentSettings___set_som(self, Value)

    def __get_csl(self):
        r"""
        Gets or sets the custom section length.


        """
        return _app._EnvironmentSettings___get_csl(self)

    def __set_csl(self, Value):
        return _app._EnvironmentSettings___set_csl(self, Value)

    def __get_transformer_loading_standard(self):
        r"""
        Gets or sets the transformer loading standard.


        """
        return _app._EnvironmentSettings___get_transformer_loading_standard(self)

    def __set_transformer_loading_standard(self, nValue):
        return _app._EnvironmentSettings___set_transformer_loading_standard(self, nValue)

    def __get_regulator_set_voltage_reference(self):
        r"""
        Gets or sets the regulator set voltage reference.


        """
        return _app._EnvironmentSettings___get_regulator_set_voltage_reference(self)

    def __set_regulator_set_voltage_reference(self, nValue):
        return _app._EnvironmentSettings___set_regulator_set_voltage_reference(self, nValue)

    def __get_converter_based_der_models_limit(self):
        r"""
        Gets or sets the converter-based DER models limit.


        """
        return _app._EnvironmentSettings___get_converter_based_der_models_limit(self)

    def __set_converter_based_der_models_limit(self, nValue):
        return _app._EnvironmentSettings___set_converter_based_der_models_limit(self, nValue)

    def HasDataValidationOption(self, arg2):
        r"""
        Indicates if the specified data validation option is enabled.


        """
        return _app._EnvironmentSettings_HasDataValidationOption(self, arg2)

    def SetDataValidationOption(self, Value, Enable):
        r"""
        Sets the status (enabled or disabled) of the specified data validation option.


        """
        return _app._EnvironmentSettings_SetDataValidationOption(self, Value, Enable)

    SystemOfUnits = property(__get_sou, __set_sou)
    LengthOfUnits = property(__get_lou, __set_lou)
    SystemFrequency = property(__get_sf, __set_sf)
    BasePower_AC_MVA = property(__get_bpacmva, __set_bpacmva)
    BasePower_DC_KW = property(__get_bpdckw, __set_bpdckw)
    BaseVoltage = property(__get_bv, __set_bv)
    OutsideTemperature = property(__get_ot, __set_ot)
    AverageEarthResistivity = property(__get_aer, __set_aer)
    ConductorResistance = property(__get_cr, __set_cr)
    Embedded = property(__get_emb, __set_emb)
    Batch = property(__get_batch, __set_batch)
    SectionOrientationMode = property(__get_som, __set_som)
    CustomSectionLength = property(__get_csl, __set_csl)
    TransformerLoadingStandard = property(__get_transformer_loading_standard, __set_transformer_loading_standard)
    RegulatorSetVoltageReference = property(__get_regulator_set_voltage_reference, __set_regulator_set_voltage_reference)
    ConverterBasedDERModelsLimit = property(__get_converter_based_der_models_limit, __set_converter_based_der_models_limit)


# Register _EnvironmentSettings in _app:
_app._EnvironmentSettings_swigregister(_EnvironmentSettings)
class Keyword(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.Keyword_swiginit(self, _app.new_Keyword())
    __swig_destroy__ = _app.delete_Keyword
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_app.Keyword_Name_get)
    Type = property(_app.Keyword_Type_get)
    Description = property(_app.Keyword_Description_get)
    Unit = property(_app.Keyword_Unit_get)
    Expression = property(_app.Keyword_Expression_get)
    Header = property(_app.Keyword_Header_get)
    Width = property(_app.Keyword_Width_get)
    Precision = property(_app.Keyword_Precision_get)
    IsUserDefined = property(_app.Keyword_IsUserDefined_get)
    IsReadOnly = property(_app.Keyword_IsReadOnly_get)
    DisplayType = property(_app.Keyword_DisplayType_get)

# Register Keyword in _app:
_app.Keyword_swigregister(Keyword)
class _InternalResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app._InternalResults_swiginit(self, _app.new__InternalResults())
    __swig_destroy__ = _app.delete__InternalResults

    def Add(self, *args):
        r"""
        Adds a result key to the embedded execution.

        Module: cympy.study

        Args:
           ID -> str

           Value -> int, double, bool or str

        Return type: 
           None


        """
        return _app._InternalResults_Add(self, *args)

    def AddVerification(self, Messages):
        r"""
        Adds a list of verification messages to the embedded execution.

        Module: cympy.study

        Args:
           Messages -> list of cympy.app.VerificationMessage

        Return type: 
           None


        """
        return _app._InternalResults_AddVerification(self, Messages)

    def AddPath(self, ID, Value):
        r"""
        Adds a path key to the embedded execution.

        Module: cympy.study

        Args:
           ID -> str

           Value -> str

        Return type: 
           None


        """
        return _app._InternalResults_AddPath(self, ID, Value)

    def Delete(self, ID):
        r"""
        Deletes a key in the embedded execution.

        Module: cympy.study

        Args:
           ID -> str

        Return type: 
           None


        """
        return _app._InternalResults_Delete(self, ID)

    def Get(self, ID):
        r"""
        Retrieves a key in the embedded execution.

        Module: cympy.study

        Args:
           ID -> str

        Return type: 
           str


        """
        return _app._InternalResults_Get(self, ID)

    def Clear(self):
        r"""
        Clears the keys for the embedded execution.

        Module: cympy.study

        Args:
           None

        Return type: 
           None


        """
        return _app._InternalResults_Clear(self)

    def GetCount(self):
        r"""
        Gets the count of keys in the embedded execution.

        Module: cympy.study

        Args:
           None

        Return type: 
           int


        """
        return _app._InternalResults_GetCount(self)

# Register _InternalResults in _app:
_app._InternalResults_swigregister(_InternalResults)
class Localization(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.Localization_swiginit(self, _app.new_Localization())
    __swig_destroy__ = _app.delete_Localization
    __str__ = lambda self: "(Key: '" + self.Key + "', Value: '" + self.Value + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        return _app.Localization___eq__(self, rObj)

    def __ne__(self, rObj):
        return _app.Localization___ne__(self, rObj)
    LocalizationItemType = property(_app.Localization_LocalizationItemType_get)
    DeviceType = property(_app.Localization_DeviceType_get)
    InstrumentType = property(_app.Localization_InstrumentType_get)
    EquipmentType = property(_app.Localization_EquipmentType_get)
    Key = property(_app.Localization_Key_get)
    Value = property(_app.Localization_Value_get)
    IsLink = property(_app.Localization_IsLink_get)

# Register Localization in _app:
_app.Localization_swigregister(Localization)
class Message(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.Message_swiginit(self, _app.new_Message())
    __swig_destroy__ = _app.delete_Message
    __str__ = lambda self: "'" + self.Text + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        return _app.Message___eq__(self, rObj)

    def __ne__(self, rObj):
        return _app.Message___ne__(self, rObj)

    def GetLocalizations(self):
        return _app.Message_GetLocalizations(self)

    def GetDetails(self):
        return _app.Message_GetDetails(self)

    def GetFullDetails(self):
        return _app.Message_GetFullDetails(self)
    Category = property(_app.Message_Category_get)
    Code = property(_app.Message_Code_get)
    Text = property(_app.Message_Text_get)
    Time = property(_app.Message_Time_get)
    ErrorCategory = property(_app.Message_ErrorCategory_get)
    Severity = property(_app.Message_Severity_get)

# Register Message in _app:
_app.Message_swigregister(Message)
class MultiprocessingProvider(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.MultiprocessingProvider_swiginit(self, _app.new_MultiprocessingProvider())
    __swig_destroy__ = _app.delete_MultiprocessingProvider
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    ID = property(_app.MultiprocessingProvider_ID_get)
    Name = property(_app.MultiprocessingProvider_Name_get)
    Category = property(_app.MultiprocessingProvider_Category_get)

    def Connect(self, Initialize=True):
        return _app.MultiprocessingProvider_Connect(self, Initialize)

    def Disconnect(self):
        return _app.MultiprocessingProvider_Disconnect(self)

    def IsConnected(self):
        return _app.MultiprocessingProvider_IsConnected(self)

    def IsInitialized(self):
        return _app.MultiprocessingProvider_IsInitialized(self)

# Register MultiprocessingProvider in _app:
_app.MultiprocessingProvider_swigregister(MultiprocessingProvider)
class MultiprocessingRequest(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.MultiprocessingRequest_swiginit(self, _app.new_MultiprocessingRequest())
    __swig_destroy__ = _app.delete_MultiprocessingRequest
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    ID = property(_app.MultiprocessingRequest_ID_get)
    Name = property(_app.MultiprocessingRequest_Name_get)
    PluginName = property(_app.MultiprocessingRequest_PluginName_get)
    Description = property(_app.MultiprocessingRequest_Description_get)
    UserName = property(_app.MultiprocessingRequest_UserName_get)
    StartTime = property(_app.MultiprocessingRequest_StartTime_get)

    def GetServerStatus(self):
        return _app.MultiprocessingRequest_GetServerStatus(self)

    def GetRequestStatus(self):
        return _app.MultiprocessingRequest_GetRequestStatus(self)

    def GetElapsedTime(self):
        return _app.MultiprocessingRequest_GetElapsedTime(self)

    def GetProgress(self):
        return _app.MultiprocessingRequest_GetProgress(self)

    def Cancel(self):
        return _app.MultiprocessingRequest_Cancel(self)

    def Delete(self):
        return _app.MultiprocessingRequest_Delete(self)

    def LoadResults(self):
        return _app.MultiprocessingRequest_LoadResults(self)

# Register MultiprocessingRequest in _app:
_app.MultiprocessingRequest_swigregister(MultiprocessingRequest)
class AppReportColumn(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.AppReportColumn_swiginit(self, _app.new_AppReportColumn())
    __swig_destroy__ = _app.delete_AppReportColumn
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        return _app.AppReportColumn___eq__(self, rObj)

    def __ne__(self, rObj):
        return _app.AppReportColumn___ne__(self, rObj)
    Name = property(_app.AppReportColumn_Name_get)
    UnitType = property(_app.AppReportColumn_UnitType_get)

# Register AppReportColumn in _app:
_app.AppReportColumn_swigregister(AppReportColumn)
class RowIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.RowIterator_swiginit(self, _app.new_RowIterator())
    __swig_destroy__ = _app.delete_RowIterator
    __str__ = lambda self: "'" + self.Cells + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        return _app.RowIterator___eq__(self, rObj)

    def __ne__(self, rObj):
        return _app.RowIterator___ne__(self, rObj)

    def Next(self):
        return _app.RowIterator_Next(self)
    Cells = property(_app.RowIterator_Cells_get)

# Register RowIterator in _app:
_app.RowIterator_swigregister(RowIterator)
class AppReport(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.AppReport_swiginit(self, _app.new_AppReport())
    __swig_destroy__ = _app.delete_AppReport
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        return _app.AppReport___eq__(self, rObj)

    def __ne__(self, rObj):
        return _app.AppReport___ne__(self, rObj)

    def GetHeaderGroups(self):
        return _app.AppReport_GetHeaderGroups(self)

    def GetColumns(self):
        return _app.AppReport_GetColumns(self)

    def GetRowCells(self, rowIndex):
        return _app.AppReport_GetRowCells(self, rowIndex)

    def GetRowIterator(self):
        return _app.AppReport_GetRowIterator(self)

    def GetRowCount(self):
        return _app.AppReport_GetRowCount(self)
    Name = property(_app.AppReport_Name_get)
    RowCount = property(_app.AppReport_RowCount_get)
    Index = property(_app.AppReport_Index_get)

# Register AppReport in _app:
_app.AppReport_swigregister(AppReport)
class XMLResponse(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _app.XMLResponse_swiginit(self, _app.new_XMLResponse())
    __swig_destroy__ = _app.delete_XMLResponse
    __str__ = lambda self: "(XMLResponse)"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Outputs = property(_app.XMLResponse_Outputs_get)

# Register XMLResponse in _app:
_app.XMLResponse_swigregister(XMLResponse)
class VerificationMessage(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _app.VerificationMessage_swiginit(self, _app.new_VerificationMessage(*args))
    __swig_destroy__ = _app.delete_VerificationMessage
    __str__ = lambda self: "(Message: '" + self.Message + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Message = property(_app.VerificationMessage_Message_get, _app.VerificationMessage_Message_set)
    Code = property(_app.VerificationMessage_Code_get, _app.VerificationMessage_Code_set)
    Severity = property(_app.VerificationMessage_Severity_get, _app.VerificationMessage_Severity_set)
    NetworkID = property(_app.VerificationMessage_NetworkID_get, _app.VerificationMessage_NetworkID_set)

# Register VerificationMessage in _app:
_app.VerificationMessage_swigregister(VerificationMessage)

