# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Database module.
Contains functions and classes for working with CYME databases.
"""

from sys import version_info as _swig_python_version_info
import _db

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _db.SHARED_PTR_DISOWN

SWIG_DOCSTRING_INDENT = _db.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _db.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _db.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _db.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err
class _CymPyDataObj(object):
    r"""Proxy of C++ _CymPyDataObj class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete__CymPyDataObj
    __hash__ = lambda self: hash(self.__repr__())

    def GetObjType(self):
        r"""GetObjType(_CymPyDataObj self) -> CYMString"""
        return _db._CymPyDataObj_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(_CymPyDataObj self, CYMString PropertyID) -> CYMString"""
        return _db._CymPyDataObj_GetValue(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(_CymPyDataObj self, CYMString Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, double Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, int Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, bool Value, CYMString PropertyID)
        """
        return _db._CymPyDataObj_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(_CymPyDataObj self, CYMString KeywordID) -> CYMString"""
        return _db._CymPyDataObj_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(_CymPyDataObj self, CYMString Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, double Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, int Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, bool Value, CYMString KeywordID)
        """
        return _db._CymPyDataObj_SetUDD(self, *args)

# Register _CymPyDataObj in _db:
_db._CymPyDataObj_swigregister(_CymPyDataObj)
class CustomerInfo(object):
    r"""Proxy of C++ CustomerInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(CustomerInfo self) -> CustomerInfo"""
        _db.CustomerInfo_swiginit(self, _db.new_CustomerInfo())
    __swig_destroy__ = _db.delete_CustomerInfo
    __str__ = lambda self: "(CustomerNumber: '" + self.CustomerNumber + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    CustomerNumber = property(_db.CustomerInfo_CustomerNumber_get, doc=r"""CustomerNumber : CYMString""")
    UDD = property(_db.CustomerInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_db.CustomerInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    Device = property(_db.CustomerInfo_Device_get, doc=r"""Device : DeviceInfo""")

# Register CustomerInfo in _db:
_db.CustomerInfo_swigregister(CustomerInfo)
class DeviceInfo(object):
    r"""Proxy of C++ DeviceInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(DeviceInfo self) -> DeviceInfo"""
        _db.DeviceInfo_swiginit(self, _db.new_DeviceInfo())
    __swig_destroy__ = _db.delete_DeviceInfo
    __str__ = lambda self: "(DeviceNumber: '" + self.DeviceNumber + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    DeviceType = property(_db.DeviceInfo_DeviceType_get, doc=r"""DeviceType : DeviceType::DeviceTypeEnum""")
    DeviceNumber = property(_db.DeviceInfo_DeviceNumber_get, doc=r"""DeviceNumber : CYMString""")
    UDD = property(_db.DeviceInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_db.DeviceInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    NetworkID = property(_db.DeviceInfo_NetworkID_get, doc=r"""NetworkID : CYMString""")
    SectionID = property(_db.DeviceInfo_SectionID_get, doc=r"""SectionID : CYMString""")
    FromNodeID = property(_db.DeviceInfo_FromNodeID_get, doc=r"""FromNodeID : CYMString""")
    FromNodePosition = property(_db.DeviceInfo_FromNodePosition_get, doc=r"""FromNodePosition : GUIPoint""")
    ToNodeID = property(_db.DeviceInfo_ToNodeID_get, doc=r"""ToNodeID : CYMString""")
    ToNodePosition = property(_db.DeviceInfo_ToNodePosition_get, doc=r"""ToNodePosition : GUIPoint""")

# Register DeviceInfo in _db:
_db.DeviceInfo_swigregister(DeviceInfo)
class GUIPoint(object):
    r"""Proxy of C++ GUIPoint class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(GUIPoint self) -> GUIPoint"""
        _db.GUIPoint_swiginit(self, _db.new_GUIPoint())
    __swig_destroy__ = _db.delete_GUIPoint
    __str__ = lambda self: "(Point)"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    X = property(_db.GUIPoint_X_get, doc=r"""X : double""")
    Y = property(_db.GUIPoint_Y_get, doc=r"""Y : double""")
    Lat = property(_db.GUIPoint_Lat_get, doc=r"""Lat : double""")
    Long = property(_db.GUIPoint_Long_get, doc=r"""Long : double""")

# Register GUIPoint in _db:
_db.GUIPoint_swigregister(GUIPoint)
class SectionInfo(object):
    r"""Proxy of C++ SectionInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(SectionInfo self) -> SectionInfo"""
        _db.SectionInfo_swiginit(self, _db.new_SectionInfo())
    __swig_destroy__ = _db.delete_SectionInfo
    __str__ = lambda self: "(SectionID: '" + self.SectionID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    SectionID = property(_db.SectionInfo_SectionID_get, doc=r"""SectionID : CYMString""")
    UDD = property(_db.SectionInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_db.SectionInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    NetworkID = property(_db.SectionInfo_NetworkID_get, doc=r"""NetworkID : CYMString""")
    Phase = property(_db.SectionInfo_Phase_get, doc=r"""Phase : PyPhase::PhaseEnum""")
    FromNodeID = property(_db.SectionInfo_FromNodeID_get, doc=r"""FromNodeID : CYMString""")
    FromNodePosition = property(_db.SectionInfo_FromNodePosition_get, doc=r"""FromNodePosition : GUIPoint""")
    ToNodeID = property(_db.SectionInfo_ToNodeID_get, doc=r"""ToNodeID : CYMString""")
    ToNodePosition = property(_db.SectionInfo_ToNodePosition_get, doc=r"""ToNodePosition : GUIPoint""")

# Register SectionInfo in _db:
_db.SectionInfo_swigregister(SectionInfo)
class NodeInfo(object):
    r"""Proxy of C++ NodeInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(NodeInfo self) -> NodeInfo"""
        _db.NodeInfo_swiginit(self, _db.new_NodeInfo())
    __swig_destroy__ = _db.delete_NodeInfo
    __str__ = lambda self: "(NodeID: '" + self.NodeID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    NodeID = property(_db.NodeInfo_NodeID_get, doc=r"""NodeID : CYMString""")
    NodePosition = property(_db.NodeInfo_NodePosition_get, doc=r"""NodePosition : GUIPoint""")
    Networks = property(_db.NodeInfo_Networks_get, doc=r"""Networks : std::list<(CYMString)>""")

# Register NodeInfo in _db:
_db.NodeInfo_swigregister(NodeInfo)

def Create(*args):
    r"""
    Creates a new local database.

    Module: cympy.db

    Remarks:
       - Only Microsoft Access database format is currently supported.

    Args:
       DatabaseFilePath -> str

       DatabaseType -> cympy.enums.DatabaseType (Optional, default: cympy.enums.DatabaseType.Database)

       PluginName -> str (Optional, default: '')

    Return type: 
       None


    """
    return _db.Create(*args)

def Connect(ConnectionInformation):
    r"""
    Initializes a new instance of the ConnectionInformation class.

    Module: cympy.db

    Args:
       ConnectionInformation -> cympy.db.ConnectionInformation

    Return type: 
       None


    """
    return _db.Connect(ConnectionInformation)

def Disconnect():
    r"""
    Closes the current CYME database connection.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.Disconnect()

def ConnectDatabase(ConnectionInformation):
    r"""
    Initializes a CYME database connection.

    Module: cympy.db

    Args:
       ConnectionInformation -> cympy.db.ConnectionInformation

    Return type: 
       None


    """
    return _db.ConnectDatabase(ConnectionInformation)

def ConnectDatabaseByName(Name):
    r"""
    Initializes the CYME database connection with the specified name.

    Module: cympy.db

    Args:
       Name -> str

    Return type: 
       None


    """
    return _db.ConnectDatabaseByName(Name)

def DisconnectDatabase():
    r"""
    Closes the current CYME database connection.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.DisconnectDatabase()

def ConnectLoadProfile(ProfileBillingConnectionInformation):
    r"""
    Initializes a CYME profile connection.

    Module: cympy.db

    Args:
       LoadProfileConnectionInformation -> cympy.db.LoadProfileConnectionInformation

    Return type: 
       None


    """
    return _db.ConnectLoadProfile(ProfileBillingConnectionInformation)

def ConnectLoadProfileByName(Name):
    r"""
    Initializes the CYME profile connection with the specified name.

    Module: cympy.db

    Args:
       Name -> str

    Return type: 
       None


    """
    return _db.ConnectLoadProfileByName(Name)

def DisconnectLoadProfile():
    r"""
    Closes the current CYME profile connection.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.DisconnectLoadProfile()

def ConnectResult(ResultConnectionInformation):
    r"""
    Initializes a CYME result connection.

    Module: cympy.db

    Args:
       ResultConnectionInformation -> cympy.db.ResultConnectionInformation

    Return type: 
       None


    """
    return _db.ConnectResult(ResultConnectionInformation)

def ConnectResultByName(Name):
    r"""
    Initializes the CYME result connection with the specified name.

    Module: cympy.db

    Args:
       Name -> str

    Return type: 
       None


    """
    return _db.ConnectResultByName(Name)

def DisconnectResult():
    r"""
    Closes the current CYME result connection.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.DisconnectResult()

def Update():
    r"""
    Commits current changes to the network database.

    Module: cympy.db

    Remarks:
       - A valid network database connection must have been set prior to calling this function.

    Args:
       None

    Return type: 
       None


    """
    return _db.Update()

def IsConnected():
    r"""
    Determines whether one valid database connection has been established.

    Module: cympy.db

    Args:
       None

    Return type: 
       bool


    """
    return _db.IsConnected()

def GetCurrentConnection(ActiveOnly=False):
    r"""
    Gets the current database connection information.

    Module: cympy.db

    Args:
       ActiveOnly -> bool (Optional, default: False)

    Return type: 
       cympy.db.ConnectionInformation


    """
    return _db.GetCurrentConnection(ActiveOnly)

def GetCurrentLoadProfileConnection(ActiveOnly=False):
    r"""
    Gets the current profile connection information.

    Module: cympy.db

    Args:
       ActiveOnly -> bool (Optional, default: False)

    Return type: 
       cympy.db.LoadProfileConnectionInformation


    """
    return _db.GetCurrentLoadProfileConnection(ActiveOnly)

def GetCurrentResultConnection(ActiveOnly=False):
    r"""
    Gets the current result connection information.

    Module: cympy.db

    Args:
       ActiveOnly -> bool (Optional, default: False)

    Return type: 
       cympy.db.ResultConnectionInformation


    """
    return _db.GetCurrentResultConnection(ActiveOnly)

def ListConnections():
    r"""
    Lists the connections.

    Module: cympy.db

    Args:
       None

    Return type: 
       list of cympy.db.ConnectionInformation


    """
    return _db.ListConnections()

def ListDatabaseConnections():
    r"""
    Lists the CYME database connections.

    Module: cympy.db

    Args:
       None

    Return type: 
       list of cympy.db.DatabaseConnectionInformation


    """
    return _db.ListDatabaseConnections()

def ListLoadProfileConnections():
    r"""
    Lists the CYME profile connections.

    Module: cympy.db

    Args:
       None

    Return type: 
       list of cympy.db.LoadProfileConnectionInformation


    """
    return _db.ListLoadProfileConnections()

def ListResultConnections():
    r"""
    Lists the CYME result connections.

    Module: cympy.db

    Args:
       None

    Return type: 
       list of cympy.db.ResultConnectionInformation


    """
    return _db.ListResultConnections()

def ListResults(*args):
    r"""
    Lists the CYME results.

    Module: cympy.db

    Args:
       eResultType -> cympy.enums.ResultType (Optional, default: cympy.enums.ResultType.Unknown)

       eAnalysisResultType -> cympy.enums.AnalysisResultType (Optional, default: cympy.enums.AnalysisResultType.Unknown)

       DateCreatedFrom -> int (Optional, default: 0)

       DateCreatedTo -> int (Optional, default: 0)

       Networks -> list of str (Optional, default: [])

       Name -> str (Optional, default: '')

       Category -> str (Optional, default: '')

       UseRegEx -> bool (Optional, default: false)

       Update -> bool (Optional, default: false)

    Return type: 
       list of cympy.db.CymeResult


    """
    return _db.ListResults(*args)

def ListNetworks(*args):
    r"""
    Lists all the networks identifiers available in the current database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.
       - If a project needs to be considered, use function 'ListNetworksInProject'.

    Args:
       NetworkType -> cympy.enums.NetworkType (Optional, default: cympy.enums.NetworkType.All)

       NetworkIDRegEx -> str (Optional, default: '.*')

       Group1RegEx -> str (Optional, default: '.*')

       Group2RegEx -> str (Optional, default: '.*')

       Group3RegEx -> str (Optional, default: '.*')

       Group4RegEx -> str (Optional, default: '.*')

       Group5RegEx -> str (Optional, default: '.*')

       Group6RegEx -> str (Optional, default: '.*')

       ProjectID -> str (Optional, default: '')

    Return type: 
       list of str


    """
    return _db.ListNetworks(*args)

def ListNetworksInProject(*args):
    r"""
    Lists all the networks identifiers available in the specified project.

    Module: cympy.db

    Remarks:
       - If no project database connection has been established, an exception will be raised.

    Args:
       ProjectID -> str (Optional, default: '')

    Return type: 
       list of str


    """
    return _db.ListNetworksInProject(*args)

def FindCustomerInfo(*args):
    r"""
    Retrieves information about the customers from the database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.

    Args:
       SearchText -> str

       UDD -> str (Optional, default: '')

       UseWildcards -> bool (Optional, default: False)

       MaxResults -> int (Optional, default: 0)

    Return type: 
       list of cympy.dm.CustomerInfo


    """
    return _db.FindCustomerInfo(*args)

def FindSectionInfo(*args):
    r"""
    Retrieves information about the sections from the database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.

    Args:
       SearchText -> str

       UDD -> str (Optional, default: '')

       UseWildcards -> bool (Optional, default: False)

       MaxResults -> int (Optional, default: 0)

    Return type: 
       list of cympy.dm.SectionInfo


    """
    return _db.FindSectionInfo(*args)

def FindDeviceInfo(*args):
    r"""
    Retrieves information about the devices from the database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.

    Args:
       DeviceType -> cympy.enums.DeviceType

       SearchText -> str

       UDD -> str (Optional, default: '')

       UseWildcards -> bool (Optional, default: False)

       MaxResults -> int (Optional, default: 0)

    Return type: 
       list of cympy.dm.DeviceInfo


    """
    return _db.FindDeviceInfo(*args)

def FindNodeInfo(SearchText, UseWildcards=False, MaxResults=0):
    r"""
    Retrieves information about nodes from the database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.

    Args:
       SearchText -> str

       UseWildcards -> bool (Optional, default: False)

       MaxResults -> int (Optional, default: 0)

    Return type: 
       list of cympy.dm.NodeInfo


    """
    return _db.FindNodeInfo(SearchText, UseWildcards, MaxResults)

def ListInvolvedNetworksForProject(ProjectID):
    r"""
    Lists all the networks involved for a specified project in database.

    Module: cympy.db

    Remarks:
       - If no network database connection has been established, an exception will be raised.

    Args:
       ProjectID -> str

    Return type: 
       list of str


    """
    return _db.ListInvolvedNetworksForProject(ProjectID)

def ListProjects():
    r"""
    Lists all the projects available in the current database.

    Module: cympy.db

    Remarks:
       - If no project database connection has been established, an exception will be raised.

    Args:
       None

    Return type: 
       list of cympy.db.Project


    """
    return _db.ListProjects()

def OpenProject(ProjectID):
    r"""
    Opens a project available in the current database.

    Module: cympy.db

    Remarks:
       - The return is a list of loaded network IDs.
       - If the project cannot be found in database, an exception will be raised.

    Args:
       ProjectID -> str

    Return type: 
       list of str


    """
    return _db.OpenProject(ProjectID)

def SaveProject():
    r"""
    Saves the current project.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.SaveProject()

def CloseProject():
    r"""
    Closes the current project.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.CloseProject()

def CopyProject(*args):
    r"""
    Makes a copy of a project.

    Module: cympy.db

    Remarks:
       - Returns the unique name of the copy.

    Args:
       ProjectID -> str

       CopyName -> str

    Return type: 
       str


    """
    return _db.CopyProject(*args)

def DeleteProject(ProjectID):
    r"""
    Deletes a project.

    Module: cympy.db

    Args:
       None

    Return type: 
       None


    """
    return _db.DeleteProject(ProjectID)

def ImportXML(FilePath):
    r"""
    Imports the specified XML (self-contained) data file to the current database.

    Module: cympy.db

    Remarks:
       - A valid database connection must exist before using this function. Please refer to Connect Function for more information.

    Args:
       FilePath -> str

    Return type: 
       None


    """
    return _db.ImportXML(FilePath)

def ImportASCII(*args):
    r"""
    Imports the specified ASCII data files to the current database.

    Module: cympy.db

    Remarks:
       - If one file is not specified, or if given an empty string, this data will not be imported.
       - A valid database connection must exist before using this function. Please refer to Connect Function for more information.

    Args:
       NetworkFilePath -> str

       EquipmentFilePath -> str (Optional, default: '')

       LoadFilePath -> str (Optional, default: '')

       MapFilePath -> str (Optional, default: '')

       ReliabilityFilePath -> str (Optional, default: '')

       CapacitorStatusFilePath -> str (Optional, default: '')

       MeterDemandsFilePath -> str (Optional, default: '')

       TCCFilePath -> str (Optional, default: '')

       LoadProfilesFilePath -> str (Optional, default: '')

       ClearDBType -> cympy.enums.ClearDBType (Optional, default: cympy.enums.ClearDBType.None)

    Return type: 
       None


    """
    return _db.ImportASCII(*args)

def ImportASCIIDatabase(*args):
    return _db.ImportASCIIDatabase(*args)

def ImportASCIIProfiles(*args):
    r"""
    Imports the specified ASCII file to the current profiles.

    Module: cympy.db

    Args:
       FilePath -> str

       ClearDBType -> cympy.enums.ClearDBType (Optional, default: cympy.enums.ClearDBType.None)

    Return type: 
       None


    """
    return _db.ImportASCIIProfiles(*args)

def ExportXML(FilePath):
    r"""
    Exports the current network data to a XML file.

    Module: cympy.db

    Remarks:
       - The resulting XML file is of the same format as any self-contained study of CYME (.sxst).
       - Make sure to specify a valid XML extension to the destination file path (.xml or .sxst).

    Args:
       FilePath -> str

    Return type: 
       None


    """
    return _db.ExportXML(FilePath)

def ExportASCII(*args):
    r"""
    Exports the specified network data to ASCII files.

    Module: cympy.db

    Remarks:
       - If one file is not specified, or if given an empty string, this data will not be exported.
       - Make sure to specify a valid extension to the destination file path (.txt or .json).

    Args:
       NetworkFilePath -> str

       EquipmentFilePath -> str (Optional, default: '')

       LoadFilePath -> str (Optional, default: '')

       MapFilePath -> str (Optional, default: '')

       ReliabilityFilePath -> str (Optional, default: '')

       CapacitorStatusFilePath -> str (Optional, default: '')

       MeterDemandsFilePath -> str (Optional, default: '')

       TCCFilePath -> str (Optional, default: '')

       ProfilesFilePath -> str (Optional, default: '')

    Return type: 
       None


    """
    return _db.ExportASCII(*args)

def CreateDDPInformation(PluginName, PluginFilePath):
    r"""
    CreateDDPInformation method.

    Module: cympy.db

    Args:
       PluginName -> str

       PluginFilePath -> str

    Return type: 
       cympy.db.PluginInformation


    """
    return _db.CreateDDPInformation(PluginName, PluginFilePath)

def GetDDPInformation(PluginName):
    r"""
    GetDDPInformation method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       cympy.db.PluginInformation


    """
    return _db.GetDDPInformation(PluginName)

def ConnectDDP(PluginInformation):
    r"""
    ConnectDDP method.

    Module: cympy.db

    Args:
       PluginInformation -> cympy.db.PluginInformation

    Return type: 
       None


    """
    return _db.ConnectDDP(PluginInformation)

def ListDDPConnections(ConnectedOnly=False, IncludeProfilePlugins=False):
    r"""
    Lists the Dynamic Data Pull plugin connections.

    Module: cympy.db

    Args:
       ConnectedOnly -> bool (Optional, default: False)

       IncludeProfilePlugins -> bool (Optional, default: True)

    Return type: 
       list of cympy.db.PluginConnectionInformation


    """
    return _db.ListDDPConnections(ConnectedOnly, IncludeProfilePlugins)

def ConnectDDPByName(Name):
    r"""
    ConnectDDPByName method.

    Module: cympy.db

    Args:
       Name -> str

    Return type: 
       None


    """
    return _db.ConnectDDPByName(Name)

def UpdateDDPInformation(PluginInformation):
    r"""
    UpdateDDPInformation method.

    Module: cympy.db

    Args:
       PluginInformation -> cympy.db.PluginInformation

    Return type: 
       None


    """
    return _db.UpdateDDPInformation(PluginInformation)

def DisconnectDDP(PluginName):
    r"""
    DisconnectDDP method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       None


    """
    return _db.DisconnectDDP(PluginName)

def IsDDPConnected(PluginName):
    r"""
    IsDDPConnected method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       bool


    """
    return _db.IsDDPConnected(PluginName)

def CreateDPPInformation(PluginName, PluginFilePath):
    r"""
    CreateDPPInformation method.

    Module: cympy.db

    Args:
       PluginName -> str

       PluginFilePath -> str

    Return type: 
       cympy.db.PluginInformation


    """
    return _db.CreateDPPInformation(PluginName, PluginFilePath)

def GetDPPInformation(PluginName):
    r"""
    GetDPPInformation method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       cympy.db.PluginInformation


    """
    return _db.GetDPPInformation(PluginName)

def ConnectDPP(PluginInformation):
    r"""
    ConnectDPP method.

    Module: cympy.db

    Args:
       PluginInformation -> cympy.db.PluginInformation

    Return type: 
       None


    """
    return _db.ConnectDPP(PluginInformation)

def UpdateDPPInformation(PluginInformation):
    r"""
    UpdateDPPInformation method.

    Module: cympy.db

    Args:
       PluginInformation -> cympy.db.PluginInformation

    Return type: 
       None


    """
    return _db.UpdateDPPInformation(PluginInformation)

def DisconnectDPP(PluginName):
    r"""
    DisconnectDPP method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       None


    """
    return _db.DisconnectDPP(PluginName)

def IsDPPConnected(PluginName):
    r"""
    IsDPPConnected method.

    Module: cympy.db

    Args:
       PluginName -> str

    Return type: 
       bool


    """
    return _db.IsDPPConnected(PluginName)
class DataSource(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_DataSource
    __str__ = lambda self: "DataSource"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

# Register DataSource in _db:
_db.DataSource_swigregister(DataSource)
class MDBDataSource(DataSource):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _db.MDBDataSource_swiginit(self, _db.new_MDBDataSource(*args))
    __swig_destroy__ = _db.delete_MDBDataSource
    __str__ = lambda self: "'" + self.Path + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Path = property(_db.MDBDataSource_Path_get, _db.MDBDataSource_Path_set)

# Register MDBDataSource in _db:
_db.MDBDataSource_swigregister(MDBDataSource)
class OracleDataSource(DataSource):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _db.OracleDataSource_swiginit(self, _db.new_OracleDataSource(*args))
    __swig_destroy__ = _db.delete_OracleDataSource
    __str__ = lambda self: "(ServiceName: '" + self.ServiceName + "', SchemaName: '" + self.SchemaName + "', UserID: '" + self.UserID + "', Password: '" + self.Password + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    ServiceName = property(_db.OracleDataSource_ServiceName_get, _db.OracleDataSource_ServiceName_set)
    SchemaName = property(_db.OracleDataSource_SchemaName_get, _db.OracleDataSource_SchemaName_set)
    UserID = property(_db.OracleDataSource_UserID_get, _db.OracleDataSource_UserID_set)
    Password = property(_db.OracleDataSource_Password_get, _db.OracleDataSource_Password_set)

# Register OracleDataSource in _db:
_db.OracleDataSource_swigregister(OracleDataSource)
class SQLServerDataSource(DataSource):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _db.SQLServerDataSource_swiginit(self, _db.new_SQLServerDataSource(*args))
    __swig_destroy__ = _db.delete_SQLServerDataSource
    __str__ = lambda self: "(DatabaseName: '" + self.DatabaseName + "', ServerName: '" + self.ServerName + "', UserID: '" + self.UserID + "', WindowsAuthentication: " + str( self.WindowsAuthentication ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    DatabaseName = property(_db.SQLServerDataSource_DatabaseName_get, _db.SQLServerDataSource_DatabaseName_set)
    ServerName = property(_db.SQLServerDataSource_ServerName_get, _db.SQLServerDataSource_ServerName_set)
    UserID = property(_db.SQLServerDataSource_UserID_get, _db.SQLServerDataSource_UserID_set)
    Password = property(_db.SQLServerDataSource_Password_get, _db.SQLServerDataSource_Password_set)
    WindowsAuthentication = property(_db.SQLServerDataSource_WindowsAuthentication_get, _db.SQLServerDataSource_WindowsAuthentication_set)

# Register SQLServerDataSource in _db:
_db.SQLServerDataSource_swigregister(SQLServerDataSource)
class ConnectionInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_ConnectionInformation
    __str__ = lambda self: "(Name: '" + self.Name + "', Equipment: " + str( self.Equipment ) + ", Network: " + str( self.Network ) + ", Project: " + str( self.Project ) + ", LoadProfile: " + str( self.LoadProfile ) + ", Billing: " + str( self.Billing ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __init__(self, *args):
        _db.ConnectionInformation_swiginit(self, _db.new_ConnectionInformation(*args))

    def _GetEquipment(self):
        return _db.ConnectionInformation__GetEquipment(self)

    def _SetEquipment(self, pDataSource):
        return _db.ConnectionInformation__SetEquipment(self, pDataSource)

    def _GetNetwork(self):
        return _db.ConnectionInformation__GetNetwork(self)

    def _SetNetwork(self, pDataSource):
        return _db.ConnectionInformation__SetNetwork(self, pDataSource)

    def _GetProject(self):
        return _db.ConnectionInformation__GetProject(self)

    def _SetProject(self, pDataSource):
        return _db.ConnectionInformation__SetProject(self, pDataSource)

    def _GetLoadProfile(self):
        return _db.ConnectionInformation__GetLoadProfile(self)

    def _SetLoadProfile(self, pDataSource):
        return _db.ConnectionInformation__SetLoadProfile(self, pDataSource)

    def _GetBilling(self):
        return _db.ConnectionInformation__GetBilling(self)

    def _SetBilling(self, pDataSource):
        return _db.ConnectionInformation__SetBilling(self, pDataSource)

    def SetProfilePluginTimeSeries(self):
        return _db.ConnectionInformation_SetProfilePluginTimeSeries(self)

    def SetProfilePlugin(self, PluginName):
        return _db.ConnectionInformation_SetProfilePlugin(self, PluginName)
    Name = property(_db.ConnectionInformation_Name_get, _db.ConnectionInformation_Name_set)
    LPName = property(_db.ConnectionInformation_LPName_get, _db.ConnectionInformation_LPName_set)

    Equipment = property( _GetEquipment, _SetEquipment )
    Network = property( _GetNetwork, _SetNetwork )
    Project = property( _GetProject, _SetProject )
    LoadProfile = property( _GetLoadProfile, _SetLoadProfile )
    Billing = property( _GetBilling, _SetBilling )


# Register ConnectionInformation in _db:
_db.ConnectionInformation_swigregister(ConnectionInformation)
class PluginInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _db.PluginInformation_swiginit(self, _db.new_PluginInformation())
    __swig_destroy__ = _db.delete_PluginInformation
    __str__ = lambda self: "(PluginInformation)"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def GetLoginParameter(self, ParameterName):
        return _db.PluginInformation_GetLoginParameter(self, ParameterName)

    def SetLoginParameter(self, ParameterName, ParameterValue, ValidateValue=False):
        return _db.PluginInformation_SetLoginParameter(self, ParameterName, ParameterValue, ValidateValue)

    def GetParameter(self, ParameterName):
        return _db.PluginInformation_GetParameter(self, ParameterName)

    def GetDateTimeParameter(self, *args):
        return _db.PluginInformation_GetDateTimeParameter(self, *args)

    def GetDateParameter(self, ParameterName):
        return _db.PluginInformation_GetDateParameter(self, ParameterName)

    def GetTimeParameter(self, ParameterName):
        return _db.PluginInformation_GetTimeParameter(self, ParameterName)

    def SetParameter(self, ParameterName, ParameterValue, ValidateValue=False):
        return _db.PluginInformation_SetParameter(self, ParameterName, ParameterValue, ValidateValue)

    def SetDateTimeParameter(self, *args):
        return _db.PluginInformation_SetDateTimeParameter(self, *args)

    def SetDateParameter(self, ParameterName, time, ValidateValue=False):
        return _db.PluginInformation_SetDateParameter(self, ParameterName, time, ValidateValue)

    def SetTimeParameter(self, ParameterName, time, ValidateValue=False):
        return _db.PluginInformation_SetTimeParameter(self, ParameterName, time, ValidateValue)

# Register PluginInformation in _db:
_db.PluginInformation_swigregister(PluginInformation)
class Project(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _db.Project_swiginit(self, _db.new_Project())
    __swig_destroy__ = _db.delete_Project
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    ID = property(_db.Project_ID_get)
    Name = property(_db.Project_Name_get)

# Register Project in _db:
_db.Project_swigregister(Project)
class DatabaseConnectionInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_DatabaseConnectionInformation
    __str__ = lambda self: "(Name: '" + self.Name + "', Equipment: " + str( self.Equipment ) + ", Network: " + str( self.Network ) + ", Project: " + str( self.Project ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __init__(self, *args):
        _db.DatabaseConnectionInformation_swiginit(self, _db.new_DatabaseConnectionInformation(*args))

    def _GetEquipment(self):
        return _db.DatabaseConnectionInformation__GetEquipment(self)

    def _SetEquipment(self, pDataSource):
        return _db.DatabaseConnectionInformation__SetEquipment(self, pDataSource)

    def _GetNetwork(self):
        return _db.DatabaseConnectionInformation__GetNetwork(self)

    def _SetNetwork(self, pDataSource):
        return _db.DatabaseConnectionInformation__SetNetwork(self, pDataSource)

    def _GetProject(self):
        return _db.DatabaseConnectionInformation__GetProject(self)

    def _SetProject(self, pDataSource):
        return _db.DatabaseConnectionInformation__SetProject(self, pDataSource)
    Name = property(_db.DatabaseConnectionInformation_Name_get, _db.DatabaseConnectionInformation_Name_set)

    Equipment = property( _GetEquipment, _SetEquipment )
    Network = property( _GetNetwork, _SetNetwork )
    Project = property( _GetProject, _SetProject )


# Register DatabaseConnectionInformation in _db:
_db.DatabaseConnectionInformation_swigregister(DatabaseConnectionInformation)
class LoadProfileConnectionInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_LoadProfileConnectionInformation
    __str__ = lambda self: "(Name: '" + self.Name + "', Profile: " + str( self.Profile ) + ", Billing: " + str( self.Billing ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __init__(self, *args):
        _db.LoadProfileConnectionInformation_swiginit(self, _db.new_LoadProfileConnectionInformation(*args))

    def _GetProfile(self):
        return _db.LoadProfileConnectionInformation__GetProfile(self)

    def _SetProfile(self, pDataSource):
        return _db.LoadProfileConnectionInformation__SetProfile(self, pDataSource)

    def _GetBilling(self):
        return _db.LoadProfileConnectionInformation__GetBilling(self)

    def _SetBilling(self, pDataSource):
        return _db.LoadProfileConnectionInformation__SetBilling(self, pDataSource)

    def SetPluginTimeSeries(self):
        return _db.LoadProfileConnectionInformation_SetPluginTimeSeries(self)

    def SetPlugin(self, PluginName):
        return _db.LoadProfileConnectionInformation_SetPlugin(self, PluginName)
    Name = property(_db.LoadProfileConnectionInformation_Name_get, _db.LoadProfileConnectionInformation_Name_set)

    Profile = property( _GetProfile, _SetProfile )
    Billing = property( _GetBilling, _SetBilling )


# Register LoadProfileConnectionInformation in _db:
_db.LoadProfileConnectionInformation_swigregister(LoadProfileConnectionInformation)
class ResultConnectionInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_ResultConnectionInformation
    __str__ = lambda self: "(Name: '" + self.Name + "', Result: " + str( self.Result ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __init__(self, *args):
        _db.ResultConnectionInformation_swiginit(self, _db.new_ResultConnectionInformation(*args))

    def _GetResult(self):
        return _db.ResultConnectionInformation__GetResult(self)

    def _SetResult(self, pDataSource):
        return _db.ResultConnectionInformation__SetResult(self, pDataSource)
    Name = property(_db.ResultConnectionInformation_Name_get, _db.ResultConnectionInformation_Name_set)

    Result = property( _GetResult, _SetResult )


# Register ResultConnectionInformation in _db:
_db.ResultConnectionInformation_swigregister(ResultConnectionInformation)
class PluginConnectionInformation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _db.delete_PluginConnectionInformation
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __init__(self, *args):
        _db.PluginConnectionInformation_swiginit(self, _db.new_PluginConnectionInformation(*args))
    Name = property(_db.PluginConnectionInformation_Name_get)
    Category = property(_db.PluginConnectionInformation_Category_get)
    DllPath = property(_db.PluginConnectionInformation_DllPath_get)
    PluginInfo = property(_db.PluginConnectionInformation_PluginInfo_get)

# Register PluginConnectionInformation in _db:
_db.PluginConnectionInformation_swigregister(PluginConnectionInformation)
class CymeResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _db.CymeResult_swiginit(self, _db.new_CymeResult())
    __swig_destroy__ = _db.delete_CymeResult
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    ID = property(_db.CymeResult_ID_get)
    Name = property(_db.CymeResult_Name_get)
    Category = property(_db.CymeResult_Category_get)
    Description = property(_db.CymeResult_Description_get)
    Author = property(_db.CymeResult_Author_get)
    ResultType = property(_db.CymeResult_ResultType_get)

    def LoadResults(self):
        return _db.CymeResult_LoadResults(self)

    def LoadResultsByTimeRange(self, From, To):
        return _db.CymeResult_LoadResultsByTimeRange(self, From, To)

    def Delete(self, *args):
        return _db.CymeResult_Delete(self, *args)

# Register CymeResult in _db:
_db.CymeResult_swigregister(CymeResult)

