# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Data Model module.
Contains all the data model of CYME.
"""

from sys import version_info as _swig_python_version_info
import _dm

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _dm.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _dm.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _dm.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _dm.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err
class _CymPyDataObj(object):
    r"""Proxy of C++ _CymPyDataObj class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dm.delete__CymPyDataObj
    __hash__ = lambda self: hash(self.__repr__())

    def GetObjType(self):
        r"""GetObjType(_CymPyDataObj self) -> CYMString"""
        return _dm._CymPyDataObj_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(_CymPyDataObj self, CYMString PropertyID) -> CYMString"""
        return _dm._CymPyDataObj_GetValue(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(_CymPyDataObj self, CYMString Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, double Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, int Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, bool Value, CYMString PropertyID)
        """
        return _dm._CymPyDataObj_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(_CymPyDataObj self, CYMString KeywordID) -> CYMString"""
        return _dm._CymPyDataObj_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(_CymPyDataObj self, CYMString Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, double Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, int Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, bool Value, CYMString KeywordID)
        """
        return _dm._CymPyDataObj_SetUDD(self, *args)

# Register _CymPyDataObj in _dm:
_dm._CymPyDataObj_swigregister(_CymPyDataObj)
class Equipment(_CymPyDataObj):
    r"""Proxy of C++ Equipment class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Equipment self) -> Equipment"""
        _dm.Equipment_swiginit(self, _dm.new_Equipment())
    __swig_destroy__ = _dm.delete_Equipment
    __str__ = lambda self: "(ID: '" + self.ID + "', Type: " + str( self.Type ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Equipment self, Equipment rObj) -> bool"""
        return _dm.Equipment___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Equipment self, Equipment rObj) -> bool"""
        return _dm.Equipment___ne__(self, rObj)

    def GetObjType(self):
        r"""GetObjType(Equipment self) -> CYMString"""
        return _dm.Equipment_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(Equipment self, CYMString PropertyID) -> CYMString"""
        return _dm.Equipment_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Equipment self, CYMString PropertyID) -> int"""
        return _dm.Equipment_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Equipment self, CYMString Value, CYMString PropertyID)
        SetValue(Equipment self, double Value, CYMString PropertyID)
        SetValue(Equipment self, int Value, CYMString PropertyID)
        SetValue(Equipment self, bool Value, CYMString PropertyID)
        """
        return _dm.Equipment_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Equipment self, CYMString KeywordID) -> CYMString"""
        return _dm.Equipment_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Equipment self, CYMString Value, CYMString KeywordID)
        SetUDD(Equipment self, double Value, CYMString KeywordID)
        SetUDD(Equipment self, int Value, CYMString KeywordID)
        SetUDD(Equipment self, bool Value, CYMString KeywordID)
        """
        return _dm.Equipment_SetUDD(self, *args)

    def SetSymbol(self, *args):
        r"""SetSymbol(Equipment self, int SymbolID, SymbolStatus::SymbolStatusEnum Status=Undefined)"""
        return _dm.Equipment_SetSymbol(self, *args)
    ID = property(_dm.Equipment_ID_get, doc=r"""ID : CYMString""")
    Type = property(_dm.Equipment_Type_get, doc=r"""Type : EquipmentType::EquipmentTypeEnum""")

# Register Equipment in _dm:
_dm.Equipment_swigregister(Equipment)
class LoadValue(object):
    r"""Proxy of C++ LoadValue class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(LoadValue self, double Value1, double Value2) -> LoadValue
        __init__(LoadValue self) -> LoadValue
        """
        _dm.LoadValue_swiginit(self, _dm.new_LoadValue(*args))
    __swig_destroy__ = _dm.delete_LoadValue
    __str__ = lambda self: "Value1: '" + str( self.Value1 ) + "', Value2: '" + str( self.Value2 ) + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Value1 = property(_dm.LoadValue_Value1_get, _dm.LoadValue_Value1_set, doc=r"""Value1 : double""")
    Value2 = property(_dm.LoadValue_Value2_get, _dm.LoadValue_Value2_set, doc=r"""Value2 : double""")

# Register LoadValue in _dm:
_dm.LoadValue_swigregister(LoadValue)
class Meter(object):
    r"""Proxy of C++ Meter class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Meter self) -> Meter"""
        _dm.Meter_swiginit(self, _dm.new_Meter())
    __swig_destroy__ = _dm.delete_Meter
    __hash__ = lambda self: hash(self.__repr__())
    Connected = property(_dm.Meter_Connected_get, _dm.Meter_Connected_set, doc=r"""Connected : bool""")
    IsTotalDemand = property(_dm.Meter_IsTotalDemand_get, _dm.Meter_IsTotalDemand_set, doc=r"""IsTotalDemand : bool""")
    LoadValueType = property(_dm.Meter_LoadValueType_get, _dm.Meter_LoadValueType_set, doc=r"""LoadValueType : LoadValueType::LoadValueTypeEnum""")
    DemandA = property(_dm.Meter_DemandA_get, _dm.Meter_DemandA_set, doc=r"""DemandA : p.LoadValue""")
    DemandB = property(_dm.Meter_DemandB_get, _dm.Meter_DemandB_set, doc=r"""DemandB : p.LoadValue""")
    DemandC = property(_dm.Meter_DemandC_get, _dm.Meter_DemandC_set, doc=r"""DemandC : p.LoadValue""")
    DemandTotal = property(_dm.Meter_DemandTotal_get, _dm.Meter_DemandTotal_set, doc=r"""DemandTotal : p.LoadValue""")

# Register Meter in _dm:
_dm.Meter_swigregister(Meter)
class AbnormalCondition(object):
    r"""Proxy of C++ AbnormalCondition class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(AbnormalCondition self) -> AbnormalCondition"""
        _dm.AbnormalCondition_swiginit(self, _dm.new_AbnormalCondition())
    __swig_destroy__ = _dm.delete_AbnormalCondition
    __str__ = lambda self: "Type: " + str( self.Type ) + ", ID: '" + self.ID + "', ItemType: " + str( self.ItemType )
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Type = property(_dm.AbnormalCondition_Type_get, doc=r"""Type : int""")
    ID = property(_dm.AbnormalCondition_ID_get, doc=r"""ID : CYMString""")
    ItemType = property(_dm.AbnormalCondition_ItemType_get, doc=r"""ItemType : ItemType::ItemTypeEnum""")
    NetworkID = property(_dm.AbnormalCondition_NetworkID_get, doc=r"""NetworkID : CYMString""")

# Register AbnormalCondition in _dm:
_dm.AbnormalCondition_swigregister(AbnormalCondition)
class Load(object):
    r"""Proxy of C++ Load class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Load self) -> Load"""
        _dm.Load_swiginit(self, _dm.new_Load())
    __swig_destroy__ = _dm.delete_Load
    __str__ = lambda self: "(DeviceNumber: '" + self.DeviceNumber + "', Type: " + str( self.Type ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Load self, Load rObj) -> bool"""
        return _dm.Load___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Load self, Load rObj) -> bool"""
        return _dm.Load___ne__(self, rObj)

    def GetObjType(self):
        r"""GetObjType(Load self) -> CYMString"""
        return _dm.Load_GetObjType(self)

    def ListCustomers(self):
        r"""ListCustomers(Load self) -> std::list< CYMString >"""
        return _dm.Load_ListCustomers(self)

    def DeleteCustomerLoad(self, CustomerNumber):
        r"""DeleteCustomerLoad(Load self, CYMString CustomerNumber)"""
        return _dm.Load_DeleteCustomerLoad(self, CustomerNumber)

    def AddCustomerLoad(self, CustomerNumber):
        r"""AddCustomerLoad(Load self, CYMString CustomerNumber)"""
        return _dm.Load_AddCustomerLoad(self, CustomerNumber)

    def GetValue(self, *args):
        r"""GetValue(Load self, CYMString PropertyID, CYMString CustomerNumber, PyPhase::PhaseEnum Phase, CYMString LoadModelID=_T( "DEFAULT" )) -> CYMString"""
        return _dm.Load_GetValue(self, *args)

    def SetValue(self, *args):
        r"""
        SetValue(Load self, CYMString Value, CYMString PropertyID, CYMString CustomerNumber, PyPhase::PhaseEnum Phase, CYMString LoadModelID=_T( "DEFAULT" ))
        SetValue(Load self, double Value, CYMString PropertyID, CYMString CustomerNumber, PyPhase::PhaseEnum Phase, CYMString LoadModelID=_T( "DEFAULT" ))
        SetValue(Load self, int Value, CYMString PropertyID, CYMString CustomerNumber, PyPhase::PhaseEnum Phase, CYMString LoadModelID=_T( "DEFAULT" ))
        SetValue(Load self, bool Value, CYMString PropertyID, CYMString CustomerNumber, PyPhase::PhaseEnum Phase, CYMString LoadModelID=_T( "DEFAULT" ))
        """
        return _dm.Load_SetValue(self, *args)

    def SetPhaseType(self, PhaseType):
        r"""SetPhaseType(Load self, PyPhaseType::PyPhaseTypeEnum PhaseType)"""
        return _dm.Load_SetPhaseType(self, PhaseType)

    def GetCustomerUDD(self, KeywordID, CustomerNumber):
        r"""GetCustomerUDD(Load self, CYMString KeywordID, CYMString CustomerNumber) -> CYMString"""
        return _dm.Load_GetCustomerUDD(self, KeywordID, CustomerNumber)

    def SetCustomerUDD(self, *args):
        r"""
        SetCustomerUDD(Load self, CYMString Value, CYMString KeywordID, CYMString CustomerNumber)
        SetCustomerUDD(Load self, double Value, CYMString KeywordID, CYMString CustomerNumber)
        SetCustomerUDD(Load self, int Value, CYMString KeywordID, CYMString CustomerNumber)
        SetCustomerUDD(Load self, bool Value, CYMString KeywordID, CYMString CustomerNumber)
        """
        return _dm.Load_SetCustomerUDD(self, *args)

    def GetPhaseType(self):
        r"""GetPhaseType(Load self) -> PyPhaseType::PyPhaseTypeEnum"""
        return _dm.Load_GetPhaseType(self)
    Type = property(_dm.Load_Type_get, doc=r"""Type : LoadType::LoadTypeEnum""")
    DeviceNumber = property(_dm.Load_DeviceNumber_get, doc=r"""DeviceNumber : CYMString""")

# Register Load in _dm:
_dm.Load_swigregister(Load)
class Device(_CymPyDataObj):
    r"""Proxy of C++ Device class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Device self) -> Device"""
        _dm.Device_swiginit(self, _dm.new_Device())
    __swig_destroy__ = _dm.delete_Device
    __str__ = lambda self: "(DeviceNumber: '" + self.DeviceNumber + "', DeviceType: " + str( self.DeviceType ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Device self, Device rObj) -> bool"""
        return _dm.Device___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Device self, Device rObj) -> bool"""
        return _dm.Device___ne__(self, rObj)

    def GetValue(self, PropertyID):
        r"""GetValue(Device self, CYMString PropertyID) -> CYMString"""
        return _dm.Device_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Device self, CYMString PropertyID) -> int"""
        return _dm.Device_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Device self, CYMString Value, CYMString PropertyID)
        SetValue(Device self, double Value, CYMString PropertyID)
        SetValue(Device self, int Value, CYMString PropertyID)
        SetValue(Device self, bool Value, CYMString PropertyID)
        """
        return _dm.Device_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Device self, CYMString KeywordID) -> CYMString"""
        return _dm.Device_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Device self, CYMString Value, CYMString KeywordID)
        SetUDD(Device self, double Value, CYMString KeywordID)
        SetUDD(Device self, int Value, CYMString KeywordID)
        SetUDD(Device self, bool Value, CYMString KeywordID)
        """
        return _dm.Device_SetUDD(self, *args)

    def GetObjType(self):
        r"""GetObjType(Device self) -> CYMString"""
        return _dm.Device_GetObjType(self)

    def IsModified(self):
        r"""IsModified(Device self) -> bool"""
        return _dm.Device_IsModified(self)
    DeviceNumber = property(_dm.Device_DeviceNumber_get, doc=r"""DeviceNumber : CYMString""")
    DeviceType = property(_dm.Device_DeviceType_get, doc=r"""DeviceType : DeviceType::DeviceTypeEnum""")
    SectionID = property(_dm.Device_SectionID_get, doc=r"""SectionID : CYMString""")
    NetworkID = property(_dm.Device_NetworkID_get, doc=r"""NetworkID : CYMString""")
    EquipmentID = property(_dm.Device_EquipmentID_get, doc=r"""EquipmentID : CYMString""")
    EquipmentType = property(_dm.Device_EquipmentType_get, doc=r"""EquipmentType : EquipmentType::EquipmentTypeEnum""")
    Location = property(_dm.Device_Location_get, doc=r"""Location : CymPyLocation::LocationEnum""")

# Register Device in _dm:
_dm.Device_swigregister(Device)
class Network(_CymPyDataObj):
    r"""Proxy of C++ Network class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Network self) -> Network"""
        _dm.Network_swiginit(self, _dm.new_Network())
    __swig_destroy__ = _dm.delete_Network
    __str__ = lambda self: "(ID: '" + self.NetworkID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Network self, Network rObj) -> bool"""
        return _dm.Network___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Network self, Network rObj) -> bool"""
        return _dm.Network___ne__(self, rObj)

    def GetValue(self, PropertyID):
        r"""GetValue(Network self, CYMString PropertyID) -> CYMString"""
        return _dm.Network_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Network self, CYMString PropertyID) -> int"""
        return _dm.Network_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Network self, CYMString Value, CYMString PropertyID)
        SetValue(Network self, double Value, CYMString PropertyID)
        SetValue(Network self, int Value, CYMString PropertyID)
        SetValue(Network self, bool Value, CYMString PropertyID)
        """
        return _dm.Network_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Network self, CYMString KeywordID) -> CYMString"""
        return _dm.Network_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Network self, CYMString Value, CYMString KeywordID)
        SetUDD(Network self, double Value, CYMString KeywordID)
        SetUDD(Network self, int Value, CYMString KeywordID)
        SetUDD(Network self, bool Value, CYMString KeywordID)
        """
        return _dm.Network_SetUDD(self, *args)

    def GetObjType(self):
        r"""GetObjType(Network self) -> CYMString"""
        return _dm.Network_GetObjType(self)

    def IsModified(self):
        r"""IsModified(Network self) -> bool"""
        return _dm.Network_IsModified(self)
    NetworkID = property(_dm.Network_NetworkID_get, doc=r"""NetworkID : CYMString""")
    NetworkType = property(_dm.Network_NetworkType_get, doc=r"""NetworkType : NetworkType::NetworkTypeEnum""")
    Group1 = property(_dm.Network_Group1_get, doc=r"""Group1 : CYMString""")
    Group2 = property(_dm.Network_Group2_get, doc=r"""Group2 : CYMString""")
    Group3 = property(_dm.Network_Group3_get, doc=r"""Group3 : CYMString""")
    Group4 = property(_dm.Network_Group4_get, doc=r"""Group4 : CYMString""")
    Group5 = property(_dm.Network_Group5_get, doc=r"""Group5 : CYMString""")
    Group6 = property(_dm.Network_Group6_get, doc=r"""Group6 : CYMString""")

# Register Network in _dm:
_dm.Network_swigregister(Network)
class Node(_CymPyDataObj):
    r"""Proxy of C++ CymPyNode class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Node self) -> Node"""
        _dm.Node_swiginit(self, _dm.new_Node())
    __swig_destroy__ = _dm.delete_Node
    __str__ = lambda self: "'" + self.ID + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Node self, Node rObj) -> bool"""
        return _dm.Node___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Node self, Node rObj) -> bool"""
        return _dm.Node___ne__(self, rObj)

    def GetValue(self, PropertyID):
        r"""GetValue(Node self, CYMString PropertyID) -> CYMString"""
        return _dm.Node_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Node self, CYMString PropertyID) -> int"""
        return _dm.Node_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Node self, CYMString Value, CYMString PropertyID)
        SetValue(Node self, double Value, CYMString PropertyID)
        SetValue(Node self, int Value, CYMString PropertyID)
        SetValue(Node self, bool Value, CYMString PropertyID)
        """
        return _dm.Node_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Node self, CYMString KeywordID) -> CYMString"""
        return _dm.Node_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Node self, CYMString Value, CYMString KeywordID)
        SetUDD(Node self, double Value, CYMString KeywordID)
        SetUDD(Node self, int Value, CYMString KeywordID)
        SetUDD(Node self, bool Value, CYMString KeywordID)
        """
        return _dm.Node_SetUDD(self, *args)

    def GetObjType(self):
        r"""GetObjType(Node self) -> CYMString"""
        return _dm.Node_GetObjType(self)

    def GetType(self):
        r"""GetType(Node self) -> NodeType::NodeTypeEnum"""
        return _dm.Node_GetType(self)

    def IsModified(self):
        r"""IsModified(Node self) -> bool"""
        return _dm.Node_IsModified(self)
    ID = property(_dm.Node_ID_get, _dm.Node_ID_set, doc=r"""ID : CYMString""")
    X = property(_dm.Node_X_get, _dm.Node_X_set, doc=r"""X : double""")
    Y = property(_dm.Node_Y_get, _dm.Node_Y_set, doc=r"""Y : double""")

# Register Node in _dm:
_dm.Node_swigregister(Node)
class CymPyGroup(object):
    r"""Proxy of C++ CymPyGroup class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(CymPyGroup self) -> CymPyGroup"""
        _dm.CymPyGroup_swiginit(self, _dm.new_CymPyGroup())
    __swig_destroy__ = _dm.delete_CymPyGroup
    __str__ = lambda self: "(GroupID: '" + self.GroupID + "', GroupType: " + str( self.GroupType ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(CymPyGroup self, CymPyGroup rObj) -> bool"""
        return _dm.CymPyGroup___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(CymPyGroup self, CymPyGroup rObj) -> bool"""
        return _dm.CymPyGroup___ne__(self, rObj)

    def GetValue(self, PropertyID):
        r"""GetValue(CymPyGroup self, CYMString PropertyID) -> CYMString"""
        return _dm.CymPyGroup_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(CymPyGroup self, CYMString PropertyID) -> int"""
        return _dm.CymPyGroup_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(CymPyGroup self, CYMString Value, CYMString PropertyID)
        SetValue(CymPyGroup self, double Value, CYMString PropertyID)
        SetValue(CymPyGroup self, int Value, CYMString PropertyID)
        SetValue(CymPyGroup self, bool Value, CYMString PropertyID)
        """
        return _dm.CymPyGroup_SetValue(self, *args)
    GroupID = property(_dm.CymPyGroup_GroupID_get, doc=r"""GroupID : CYMString""")
    GroupType = property(_dm.CymPyGroup_GroupType_get, doc=r"""GroupType : GroupType::GroupTypeEnum""")

# Register CymPyGroup in _dm:
_dm.CymPyGroup_swigregister(CymPyGroup)
class Section(_CymPyDataObj):
    r"""Proxy of C++ Section class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Section self) -> Section"""
        _dm.Section_swiginit(self, _dm.new_Section())
    __swig_destroy__ = _dm.delete_Section
    __str__ = lambda self: "'" + self.ID + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Section self, Section rObj) -> bool"""
        return _dm.Section___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Section self, Section rObj) -> bool"""
        return _dm.Section___ne__(self, rObj)

    def GetValue(self, PropertyID):
        r"""GetValue(Section self, CYMString PropertyID) -> CYMString"""
        return _dm.Section_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Section self, CYMString PropertyID) -> int"""
        return _dm.Section_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Section self, CYMString Value, CYMString PropertyID)
        SetValue(Section self, double Value, CYMString PropertyID)
        SetValue(Section self, int Value, CYMString PropertyID)
        SetValue(Section self, bool Value, CYMString PropertyID)
        """
        return _dm.Section_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Section self, CYMString KeywordID) -> CYMString"""
        return _dm.Section_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Section self, CYMString Value, CYMString KeywordID)
        SetUDD(Section self, double Value, CYMString KeywordID)
        SetUDD(Section self, int Value, CYMString KeywordID)
        SetUDD(Section self, bool Value, CYMString KeywordID)
        """
        return _dm.Section_SetUDD(self, *args)

    def GetObjType(self):
        r"""GetObjType(Section self) -> CYMString"""
        return _dm.Section_GetObjType(self)

    def IsModified(self):
        r"""IsModified(Section self) -> bool"""
        return _dm.Section_IsModified(self)

    def AddIntermediatePoint(self, X, Y):
        r"""AddIntermediatePoint(Section self, double X, double Y)"""
        return _dm.Section_AddIntermediatePoint(self, X, Y)

    def DeleteIntermediatePoint(self, Index):
        r"""DeleteIntermediatePoint(Section self, int Index)"""
        return _dm.Section_DeleteIntermediatePoint(self, Index)

    def ListIntermediatePoints(self):
        r"""ListIntermediatePoints(Section self) -> std::list< Point >"""
        return _dm.Section_ListIntermediatePoints(self)

    def ListDevices(self, *args):
        r"""ListDevices(Section self, DeviceType::DeviceTypeEnum DeviceType=AllDevices, CYMString DeviceNumberRegEx=_T( ".*" ), CYMString EquipmentIDRegEx=_T( ".*" )) -> std::list< Device >"""
        return _dm.Section_ListDevices(self, *args)

    def __get_len(self):
        r"""__get_len(Section self) -> double"""
        return _dm.Section___get_len(self)

    def __set_len(self, Value):
        r"""__set_len(Section self, double Value)"""
        return _dm.Section___set_len(self, Value)

    def __get_clen(self):
        r"""__get_clen(Section self) -> double"""
        return _dm.Section___get_clen(self)

    def __set_clen(self, Value):
        r"""__set_clen(Section self, double Value)"""
        return _dm.Section___set_clen(self, Value)

    Length = property( __get_len, __set_len )
    CalculatedLength = property( __get_clen, __set_clen )

    ID = property(_dm.Section_ID_get, doc=r"""ID : CYMString""")
    FromNode = property(_dm.Section_FromNode_get, doc=r"""FromNode : p.CymPyNode""")
    ToNode = property(_dm.Section_ToNode_get, doc=r"""ToNode : p.CymPyNode""")
    TertiaryNode = property(_dm.Section_TertiaryNode_get, doc=r"""TertiaryNode : p.CymPyNode""")

# Register Section in _dm:
_dm.Section_swigregister(Section)
class Instrument(_CymPyDataObj):
    r"""Proxy of C++ Instrument class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Instrument self) -> Instrument"""
        _dm.Instrument_swiginit(self, _dm.new_Instrument())
    __swig_destroy__ = _dm.delete_Instrument
    __str__ = lambda self: "(InstrumentNumber: '" + self.InstrumentNumber + "', InstrumentType: " + str( self.InstrumentType ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Instrument self, Instrument rObj) -> bool"""
        return _dm.Instrument___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Instrument self, Instrument rObj) -> bool"""
        return _dm.Instrument___ne__(self, rObj)

    def GetObjType(self):
        r"""GetObjType(Instrument self) -> CYMString"""
        return _dm.Instrument_GetObjType(self)

    def IsModified(self):
        r"""IsModified(Instrument self) -> bool"""
        return _dm.Instrument_IsModified(self)

    def GetDevice(self):
        r"""GetDevice(Instrument self) -> Device"""
        return _dm.Instrument_GetDevice(self)

    def GetNode(self):
        r"""GetNode(Instrument self) -> Node"""
        return _dm.Instrument_GetNode(self)

    def GetValue(self, PropertyID):
        r"""GetValue(Instrument self, CYMString PropertyID) -> CYMString"""
        return _dm.Instrument_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Instrument self, CYMString PropertyID) -> int"""
        return _dm.Instrument_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Instrument self, CYMString Value, CYMString PropertyID)
        SetValue(Instrument self, double Value, CYMString PropertyID)
        SetValue(Instrument self, int Value, CYMString PropertyID)
        SetValue(Instrument self, bool Value, CYMString PropertyID)
        """
        return _dm.Instrument_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Instrument self, CYMString KeywordID) -> CYMString"""
        return _dm.Instrument_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Instrument self, CYMString Value, CYMString KeywordID)
        SetUDD(Instrument self, double Value, CYMString KeywordID)
        SetUDD(Instrument self, int Value, CYMString KeywordID)
        SetUDD(Instrument self, bool Value, CYMString KeywordID)
        """
        return _dm.Instrument_SetUDD(self, *args)
    InstrumentNumber = property(_dm.Instrument_InstrumentNumber_get, doc=r"""InstrumentNumber : CYMString""")
    InstrumentType = property(_dm.Instrument_InstrumentType_get, doc=r"""InstrumentType : InstrumentType::InstrumentTypeEnum""")

# Register Instrument in _dm:
_dm.Instrument_swigregister(Instrument)
class LoadModel(object):
    r"""Proxy of C++ LoadModel class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(LoadModel self) -> LoadModel"""
        _dm.LoadModel_swiginit(self, _dm.new_LoadModel())
    __swig_destroy__ = _dm.delete_LoadModel
    __str__ = lambda self: "(Name: '" + self.Name + "', ID: " + str( self.ID ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_dm.LoadModel_Name_get, _dm.LoadModel_Name_set, doc=r"""Name : CYMString""")
    ID = property(_dm.LoadModel_ID_get, _dm.LoadModel_ID_set, doc=r"""ID : int""")

# Register LoadModel in _dm:
_dm.LoadModel_swigregister(LoadModel)
class CustomerType(object):
    r"""Proxy of C++ CustomerType class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(CustomerType self) -> CustomerType"""
        _dm.CustomerType_swiginit(self, _dm.new_CustomerType())
    __swig_destroy__ = _dm.delete_CustomerType
    __str__ = lambda self: "(Name: '" + self.Name + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def GetValue(self, PropertyID):
        r"""GetValue(CustomerType self, CYMString PropertyID) -> CYMString"""
        return _dm.CustomerType_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(CustomerType self, CYMString PropertyID) -> int"""
        return _dm.CustomerType_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(CustomerType self, CYMString Value, CYMString PropertyID)
        SetValue(CustomerType self, double Value, CYMString PropertyID)
        SetValue(CustomerType self, int Value, CYMString PropertyID)
        SetValue(CustomerType self, bool Value, CYMString PropertyID)
        """
        return _dm.CustomerType_SetValue(self, *args)
    Name = property(_dm.CustomerType_Name_get, _dm.CustomerType_Name_set, doc=r"""Name : CYMString""")

# Register CustomerType in _dm:
_dm.CustomerType_swigregister(CustomerType)
class Point(object):
    r"""Proxy of C++ Point class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Point self) -> Point"""
        _dm.Point_swiginit(self, _dm.new_Point())
    __swig_destroy__ = _dm.delete_Point

    def __eq__(self, rObj):
        r"""__eq__(Point self, Point rObj) -> bool"""
        return _dm.Point___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Point self, Point rObj) -> bool"""
        return _dm.Point___ne__(self, rObj)

    def cymprint(self):
    	return "(X: " + str(self.X) + ", Y: " + str(self.Y) + ")"

    __str__ = cymprint
    __repr__  = cymprint
    del cymprint

    X = property(_dm.Point_X_get, _dm.Point_X_set, doc=r"""X : double""")
    Y = property(_dm.Point_Y_get, _dm.Point_Y_set, doc=r"""Y : double""")

# Register Point in _dm:
_dm.Point_swigregister(Point)
class CymPyCustomer(object):
    r"""Proxy of C++ CymPyCustomer class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(CymPyCustomer self) -> CymPyCustomer"""
        _dm.CymPyCustomer_swiginit(self, _dm.new_CymPyCustomer())
    __swig_destroy__ = _dm.delete_CymPyCustomer
    __str__ = lambda self: "(CustomerNumber: '" + self.CustomerNumber + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(CymPyCustomer self, CymPyCustomer rObj) -> bool"""
        return _dm.CymPyCustomer___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(CymPyCustomer self, CymPyCustomer rObj) -> bool"""
        return _dm.CymPyCustomer___ne__(self, rObj)
    CustomerNumber = property(_dm.CymPyCustomer_CustomerNumber_get, doc=r"""CustomerNumber : CYMString""")
    DeviceNumber = property(_dm.CymPyCustomer_DeviceNumber_get, doc=r"""DeviceNumber : CYMString""")
    DeviceType = property(_dm.CymPyCustomer_DeviceType_get, doc=r"""DeviceType : DeviceType::DeviceTypeEnum""")

# Register CymPyCustomer in _dm:
_dm.CymPyCustomer_swigregister(CymPyCustomer)
class CustomerInfo(object):
    r"""Proxy of C++ CustomerInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(CustomerInfo self) -> CustomerInfo"""
        _dm.CustomerInfo_swiginit(self, _dm.new_CustomerInfo())
    __swig_destroy__ = _dm.delete_CustomerInfo
    __str__ = lambda self: "(CustomerNumber: '" + self.CustomerNumber + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    CustomerNumber = property(_dm.CustomerInfo_CustomerNumber_get, doc=r"""CustomerNumber : CYMString""")
    UDD = property(_dm.CustomerInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_dm.CustomerInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    Device = property(_dm.CustomerInfo_Device_get, doc=r"""Device : DeviceInfo""")

# Register CustomerInfo in _dm:
_dm.CustomerInfo_swigregister(CustomerInfo)
class DeviceInfo(object):
    r"""Proxy of C++ DeviceInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(DeviceInfo self) -> DeviceInfo"""
        _dm.DeviceInfo_swiginit(self, _dm.new_DeviceInfo())
    __swig_destroy__ = _dm.delete_DeviceInfo
    __str__ = lambda self: "(DeviceNumber: '" + self.DeviceNumber + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    DeviceType = property(_dm.DeviceInfo_DeviceType_get, doc=r"""DeviceType : DeviceType::DeviceTypeEnum""")
    DeviceNumber = property(_dm.DeviceInfo_DeviceNumber_get, doc=r"""DeviceNumber : CYMString""")
    UDD = property(_dm.DeviceInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_dm.DeviceInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    NetworkID = property(_dm.DeviceInfo_NetworkID_get, doc=r"""NetworkID : CYMString""")
    SectionID = property(_dm.DeviceInfo_SectionID_get, doc=r"""SectionID : CYMString""")
    FromNodeID = property(_dm.DeviceInfo_FromNodeID_get, doc=r"""FromNodeID : CYMString""")
    FromNodePosition = property(_dm.DeviceInfo_FromNodePosition_get, doc=r"""FromNodePosition : GUIPoint""")
    ToNodeID = property(_dm.DeviceInfo_ToNodeID_get, doc=r"""ToNodeID : CYMString""")
    ToNodePosition = property(_dm.DeviceInfo_ToNodePosition_get, doc=r"""ToNodePosition : GUIPoint""")

# Register DeviceInfo in _dm:
_dm.DeviceInfo_swigregister(DeviceInfo)
class GUIPoint(object):
    r"""Proxy of C++ GUIPoint class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(GUIPoint self) -> GUIPoint"""
        _dm.GUIPoint_swiginit(self, _dm.new_GUIPoint())
    __swig_destroy__ = _dm.delete_GUIPoint
    __str__ = lambda self: "(Point)"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    X = property(_dm.GUIPoint_X_get, doc=r"""X : double""")
    Y = property(_dm.GUIPoint_Y_get, doc=r"""Y : double""")
    Lat = property(_dm.GUIPoint_Lat_get, doc=r"""Lat : double""")
    Long = property(_dm.GUIPoint_Long_get, doc=r"""Long : double""")

# Register GUIPoint in _dm:
_dm.GUIPoint_swigregister(GUIPoint)
class SectionInfo(object):
    r"""Proxy of C++ SectionInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(SectionInfo self) -> SectionInfo"""
        _dm.SectionInfo_swiginit(self, _dm.new_SectionInfo())
    __swig_destroy__ = _dm.delete_SectionInfo
    __str__ = lambda self: "(SectionID: '" + self.SectionID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    SectionID = property(_dm.SectionInfo_SectionID_get, doc=r"""SectionID : CYMString""")
    UDD = property(_dm.SectionInfo_UDD_get, doc=r"""UDD : CYMString""")
    UDDValue = property(_dm.SectionInfo_UDDValue_get, doc=r"""UDDValue : CYMString""")
    NetworkID = property(_dm.SectionInfo_NetworkID_get, doc=r"""NetworkID : CYMString""")
    Phase = property(_dm.SectionInfo_Phase_get, doc=r"""Phase : PyPhase::PhaseEnum""")
    FromNodeID = property(_dm.SectionInfo_FromNodeID_get, doc=r"""FromNodeID : CYMString""")
    FromNodePosition = property(_dm.SectionInfo_FromNodePosition_get, doc=r"""FromNodePosition : GUIPoint""")
    ToNodeID = property(_dm.SectionInfo_ToNodeID_get, doc=r"""ToNodeID : CYMString""")
    ToNodePosition = property(_dm.SectionInfo_ToNodePosition_get, doc=r"""ToNodePosition : GUIPoint""")

# Register SectionInfo in _dm:
_dm.SectionInfo_swigregister(SectionInfo)
class NodeInfo(object):
    r"""Proxy of C++ NodeInfo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(NodeInfo self) -> NodeInfo"""
        _dm.NodeInfo_swiginit(self, _dm.new_NodeInfo())
    __swig_destroy__ = _dm.delete_NodeInfo
    __str__ = lambda self: "(NodeID: '" + self.NodeID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    NodeID = property(_dm.NodeInfo_NodeID_get, doc=r"""NodeID : CYMString""")
    NodePosition = property(_dm.NodeInfo_NodePosition_get, doc=r"""NodePosition : GUIPoint""")
    Networks = property(_dm.NodeInfo_Networks_get, doc=r"""Networks : std::list<(CYMString)>""")

# Register NodeInfo in _dm:
_dm.NodeInfo_swigregister(NodeInfo)

def Describe(ObjectType):
    r"""
    Provides information about the properties of an object. The property details can be used to get or set an object attribute.

    Module: cympy.dm

    Args:
       ObjectType -> str

    Return type: 
       list of cympy.dm.DescribeObj


    """
    return _dm.Describe(ObjectType)
class DescribeObj(object):
    r"""Proxy of C++ DescribeObj class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(DescribeObj self) -> DescribeObj"""
        _dm.DescribeObj_swiginit(self, _dm.new_DescribeObj())
    __swig_destroy__ = _dm.delete_DescribeObj
    __str__ = lambda self: "(Name: '" + self.Name + "', Type: '" + self.Type + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_dm.DescribeObj_Name_get, doc=r"""Name : CYMString""")
    Type = property(_dm.DescribeObj_Type_get, doc=r"""Type : CYMString""")
    Description = property(_dm.DescribeObj_Description_get, doc=r"""Description : CYMString""")
    DefaultValue = property(_dm.DescribeObj_DefaultValue_get, doc=r"""DefaultValue : CYMString""")
    Units = property(_dm.DescribeObj_Units_get, doc=r"""Units : CYMString""")

# Register DescribeObj in _dm:
_dm.DescribeObj_swigregister(DescribeObj)

