# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Equipment module.
Contains functions and classes for working with CYME equipment.
"""

from sys import version_info as _swig_python_version_info
import _eq

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _eq.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _eq.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _eq.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _eq.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err
class _CymPyDataObj(object):
    r"""Proxy of C++ _CymPyDataObj class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _eq.delete__CymPyDataObj
    __hash__ = lambda self: hash(self.__repr__())

    def GetObjType(self):
        r"""GetObjType(_CymPyDataObj self) -> CYMString"""
        return _eq._CymPyDataObj_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(_CymPyDataObj self, CYMString PropertyID) -> CYMString"""
        return _eq._CymPyDataObj_GetValue(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(_CymPyDataObj self, CYMString Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, double Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, int Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, bool Value, CYMString PropertyID)
        """
        return _eq._CymPyDataObj_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(_CymPyDataObj self, CYMString KeywordID) -> CYMString"""
        return _eq._CymPyDataObj_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(_CymPyDataObj self, CYMString Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, double Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, int Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, bool Value, CYMString KeywordID)
        """
        return _eq._CymPyDataObj_SetUDD(self, *args)

# Register _CymPyDataObj in _eq:
_eq._CymPyDataObj_swigregister(_CymPyDataObj)
class Equipment(_CymPyDataObj):
    r"""Proxy of C++ Equipment class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Equipment self) -> Equipment"""
        _eq.Equipment_swiginit(self, _eq.new_Equipment())
    __swig_destroy__ = _eq.delete_Equipment
    __str__ = lambda self: "(ID: '" + self.ID + "', Type: " + str( self.Type ) + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def __eq__(self, rObj):
        r"""__eq__(Equipment self, Equipment rObj) -> bool"""
        return _eq.Equipment___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Equipment self, Equipment rObj) -> bool"""
        return _eq.Equipment___ne__(self, rObj)

    def GetObjType(self):
        r"""GetObjType(Equipment self) -> CYMString"""
        return _eq.Equipment_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(Equipment self, CYMString PropertyID) -> CYMString"""
        return _eq.Equipment_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        r"""Execute(Equipment self, CYMString PropertyID) -> int"""
        return _eq.Equipment_Execute(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(Equipment self, CYMString Value, CYMString PropertyID)
        SetValue(Equipment self, double Value, CYMString PropertyID)
        SetValue(Equipment self, int Value, CYMString PropertyID)
        SetValue(Equipment self, bool Value, CYMString PropertyID)
        """
        return _eq.Equipment_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(Equipment self, CYMString KeywordID) -> CYMString"""
        return _eq.Equipment_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(Equipment self, CYMString Value, CYMString KeywordID)
        SetUDD(Equipment self, double Value, CYMString KeywordID)
        SetUDD(Equipment self, int Value, CYMString KeywordID)
        SetUDD(Equipment self, bool Value, CYMString KeywordID)
        """
        return _eq.Equipment_SetUDD(self, *args)

    def SetSymbol(self, *args):
        r"""SetSymbol(Equipment self, int SymbolID, SymbolStatus::SymbolStatusEnum Status=Undefined)"""
        return _eq.Equipment_SetSymbol(self, *args)
    ID = property(_eq.Equipment_ID_get, doc=r"""ID : CYMString""")
    Type = property(_eq.Equipment_Type_get, doc=r"""Type : EquipmentType::EquipmentTypeEnum""")

# Register Equipment in _eq:
_eq.Equipment_swigregister(Equipment)

def Delete(EquipmentID, EquipmentType):
    r"""
    Deletes an existing equipment from the library.

    Module: cympy.eq

    Remarks:
       - If the equipment cannot be deleted or doesn't exist, an exception is thrown.

    Args:
       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       None


    """
    return _eq.Delete(EquipmentID, EquipmentType)

def GetEquipment(EquipmentID, EquipmentType):
    r"""
    Gets a specific equipment.

    Module: cympy.eq

    Args:
       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       cympy.eq.Equipment


    """
    return _eq.GetEquipment(EquipmentID, EquipmentType)

def Add(*args):
    r"""
    Adds a new equipment to the library.

    Module: cympy.eq

    Remarks:
       - The properties of the newly created equipment are all set to default values. Use the SetValue function afterwards to modify the properties that you want.

    Args:
       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       cympy.eq.Equipment


    """
    return _eq.Add(*args)

def ListEquipments(*args):
    r"""
    Lists all equipments from the library.

    Module: cympy.eq

    Args:
       EquipmentType -> cympy.enums.EquipmentType

       EquipmentIdFilter -> str (Optional, default: '.*')

    Return type: 
       list of cympy.eq.Equipment


    """
    return _eq.ListEquipments(*args)

def GetValue(PropertyID, EquipmentID, EquipmentType):
    r"""
    Gets a specific property value from an equipment.

    Module: cympy.eq

    Args:
       PropertyID -> str

       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       str


    """
    return _eq.GetValue(PropertyID, EquipmentID, EquipmentType)

def Execute(PropertyID, EquipmentID, EquipmentType):
    r"""
    Executes an operation on the specified equipment.

    Module: cympy.eq

    Args:
       PropertyID -> str

       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       int


    """
    return _eq.Execute(PropertyID, EquipmentID, EquipmentType)

def SetValue(*args):
    r"""
    Sets the value for a specific property of an equipment.

    Module: cympy.eq

    Args:
       Value -> str, float, int or double

       PropertyID -> str

       EquipmentID -> str

       EquipmentType -> cympy.enums.EquipmentType

    Return type: 
       None


    """
    return _eq.SetValue(*args)

