# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Error Manager module.
Contains functions and classes for working with CYME errors and exceptions.
"""

from sys import version_info as _swig_python_version_info
import _err

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _err.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _err.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _err.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _err.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums

def Add(*args):
    r"""
    Adds an error to the user-defined error list.

    Module: cympy.err

    Args:
       Message -> str

       Severity -> cympy.enums.Severity (Optional, default: cympy.enums.Severity.Error)

    Return type: 
       None


    """
    return _err.Add(*args)

def Clear():
    r"""
    Clears the user-defined error list.

    Module: cympy.err

    Args:
       None

    Return type: 
       None


    """
    return _err.Clear()
class CymError(Exception):
    r"""Proxy of C++ CymError class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(CymError self) -> CymError
        __init__(CymError self, CYMString arg2) -> CymError
        """
        _err.CymError_swiginit(self, _err.new_CymError(*args))
    __swig_destroy__ = _err.delete_CymError
    __hash__ = lambda self: hash(self.__repr__())

    def GetMessage(self):
        r"""GetMessage(CymError self) -> CYMString"""
        return _err.CymError_GetMessage(self)

    __str__ = GetMessage
    __repr__  = GetMessage


# Register CymError in _err:
_err.CymError_swigregister(CymError)

