# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Report Manager module.
Contains functions and classes for generating reports.
"""

from sys import version_info as _swig_python_version_info
import _rm

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _rm.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _rm.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _rm.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _rm.SWIG_DOCSTRING_ARGUMENTS_TITLE

class SwigPyIterator(object):
    r"""Proxy of C++ swig::SwigPyIterator class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rm.delete_SwigPyIterator

    def value(self):
        r"""value(SwigPyIterator self) -> PyObject *"""
        return _rm.SwigPyIterator_value(self)

    def incr(self, n=1):
        r"""incr(SwigPyIterator self, size_t n=1) -> SwigPyIterator"""
        return _rm.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        r"""decr(SwigPyIterator self, size_t n=1) -> SwigPyIterator"""
        return _rm.SwigPyIterator_decr(self, n)

    def distance(self, x):
        r"""distance(SwigPyIterator self, SwigPyIterator x) -> ptrdiff_t"""
        return _rm.SwigPyIterator_distance(self, x)

    def equal(self, x):
        r"""equal(SwigPyIterator self, SwigPyIterator x) -> bool"""
        return _rm.SwigPyIterator_equal(self, x)

    def copy(self):
        r"""copy(SwigPyIterator self) -> SwigPyIterator"""
        return _rm.SwigPyIterator_copy(self)

    def next(self):
        r"""next(SwigPyIterator self) -> PyObject *"""
        return _rm.SwigPyIterator_next(self)

    def __next__(self):
        r"""__next__(SwigPyIterator self) -> PyObject *"""
        return _rm.SwigPyIterator___next__(self)

    def previous(self):
        r"""previous(SwigPyIterator self) -> PyObject *"""
        return _rm.SwigPyIterator_previous(self)

    def advance(self, n):
        r"""advance(SwigPyIterator self, ptrdiff_t n) -> SwigPyIterator"""
        return _rm.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        r"""__eq__(SwigPyIterator self, SwigPyIterator x) -> bool"""
        return _rm.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        r"""__ne__(SwigPyIterator self, SwigPyIterator x) -> bool"""
        return _rm.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        r"""__iadd__(SwigPyIterator self, ptrdiff_t n) -> SwigPyIterator"""
        return _rm.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        r"""__isub__(SwigPyIterator self, ptrdiff_t n) -> SwigPyIterator"""
        return _rm.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        r"""__add__(SwigPyIterator self, ptrdiff_t n) -> SwigPyIterator"""
        return _rm.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        r"""
        __sub__(SwigPyIterator self, ptrdiff_t n) -> SwigPyIterator
        __sub__(SwigPyIterator self, SwigPyIterator x) -> ptrdiff_t
        """
        return _rm.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _rm:
_rm.SwigPyIterator_swigregister(SwigPyIterator)
import cympy.enums
import cympy.err
class ListPoint(object):
    r"""Proxy of C++ std::list< Point > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        r"""iterator(ListPoint self) -> SwigPyIterator"""
        return _rm.ListPoint_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        r"""__nonzero__(ListPoint self) -> bool"""
        return _rm.ListPoint___nonzero__(self)

    def __bool__(self):
        r"""__bool__(ListPoint self) -> bool"""
        return _rm.ListPoint___bool__(self)

    def __len__(self):
        r"""__len__(ListPoint self) -> std::list< Point >::size_type"""
        return _rm.ListPoint___len__(self)

    def __getslice__(self, i, j):
        r"""__getslice__(ListPoint self, std::list< Point >::difference_type i, std::list< Point >::difference_type j) -> ListPoint"""
        return _rm.ListPoint___getslice__(self, i, j)

    def __setslice__(self, *args):
        r"""
        __setslice__(ListPoint self, std::list< Point >::difference_type i, std::list< Point >::difference_type j)
        __setslice__(ListPoint self, std::list< Point >::difference_type i, std::list< Point >::difference_type j, ListPoint v)
        """
        return _rm.ListPoint___setslice__(self, *args)

    def __delslice__(self, i, j):
        r"""__delslice__(ListPoint self, std::list< Point >::difference_type i, std::list< Point >::difference_type j)"""
        return _rm.ListPoint___delslice__(self, i, j)

    def __delitem__(self, *args):
        r"""
        __delitem__(ListPoint self, std::list< Point >::difference_type i)
        __delitem__(ListPoint self, SWIGPY_SLICEOBJECT * slice)
        """
        return _rm.ListPoint___delitem__(self, *args)

    def __getitem__(self, *args):
        r"""
        __getitem__(ListPoint self, SWIGPY_SLICEOBJECT * slice) -> ListPoint
        __getitem__(ListPoint self, std::list< Point >::difference_type i) -> Point
        """
        return _rm.ListPoint___getitem__(self, *args)

    def __setitem__(self, *args):
        r"""
        __setitem__(ListPoint self, SWIGPY_SLICEOBJECT * slice, ListPoint v)
        __setitem__(ListPoint self, SWIGPY_SLICEOBJECT * slice)
        __setitem__(ListPoint self, std::list< Point >::difference_type i, Point x)
        """
        return _rm.ListPoint___setitem__(self, *args)

    def pop(self):
        r"""pop(ListPoint self) -> Point"""
        return _rm.ListPoint_pop(self)

    def append(self, x):
        r"""append(ListPoint self, Point x)"""
        return _rm.ListPoint_append(self, x)

    def empty(self):
        r"""empty(ListPoint self) -> bool"""
        return _rm.ListPoint_empty(self)

    def size(self):
        r"""size(ListPoint self) -> std::list< Point >::size_type"""
        return _rm.ListPoint_size(self)

    def swap(self, v):
        r"""swap(ListPoint self, ListPoint v)"""
        return _rm.ListPoint_swap(self, v)

    def begin(self):
        r"""begin(ListPoint self) -> std::list< Point >::iterator"""
        return _rm.ListPoint_begin(self)

    def end(self):
        r"""end(ListPoint self) -> std::list< Point >::iterator"""
        return _rm.ListPoint_end(self)

    def rbegin(self):
        r"""rbegin(ListPoint self) -> std::list< Point >::reverse_iterator"""
        return _rm.ListPoint_rbegin(self)

    def rend(self):
        r"""rend(ListPoint self) -> std::list< Point >::reverse_iterator"""
        return _rm.ListPoint_rend(self)

    def clear(self):
        r"""clear(ListPoint self)"""
        return _rm.ListPoint_clear(self)

    def get_allocator(self):
        r"""get_allocator(ListPoint self) -> std::list< Point >::allocator_type"""
        return _rm.ListPoint_get_allocator(self)

    def pop_back(self):
        r"""pop_back(ListPoint self)"""
        return _rm.ListPoint_pop_back(self)

    def erase(self, *args):
        r"""
        erase(ListPoint self, std::list< Point >::iterator pos) -> std::list< Point >::iterator
        erase(ListPoint self, std::list< Point >::iterator first, std::list< Point >::iterator last) -> std::list< Point >::iterator
        """
        return _rm.ListPoint_erase(self, *args)

    def __init__(self, *args):
        r"""
        __init__(ListPoint self) -> ListPoint
        __init__(ListPoint self, ListPoint other) -> ListPoint
        __init__(ListPoint self, std::list< Point >::size_type size) -> ListPoint
        __init__(ListPoint self, std::list< Point >::size_type size, Point value) -> ListPoint
        """
        _rm.ListPoint_swiginit(self, _rm.new_ListPoint(*args))

    def push_back(self, x):
        r"""push_back(ListPoint self, Point x)"""
        return _rm.ListPoint_push_back(self, x)

    def front(self):
        r"""front(ListPoint self) -> Point"""
        return _rm.ListPoint_front(self)

    def back(self):
        r"""back(ListPoint self) -> Point"""
        return _rm.ListPoint_back(self)

    def assign(self, n, x):
        r"""assign(ListPoint self, std::list< Point >::size_type n, Point x)"""
        return _rm.ListPoint_assign(self, n, x)

    def resize(self, *args):
        r"""
        resize(ListPoint self, std::list< Point >::size_type new_size)
        resize(ListPoint self, std::list< Point >::size_type new_size, Point x)
        """
        return _rm.ListPoint_resize(self, *args)

    def insert(self, *args):
        r"""
        insert(ListPoint self, std::list< Point >::iterator pos, Point x) -> std::list< Point >::iterator
        insert(ListPoint self, std::list< Point >::iterator pos, std::list< Point >::size_type n, Point x)
        """
        return _rm.ListPoint_insert(self, *args)

    def pop_front(self):
        r"""pop_front(ListPoint self)"""
        return _rm.ListPoint_pop_front(self)

    def push_front(self, x):
        r"""push_front(ListPoint self, Point x)"""
        return _rm.ListPoint_push_front(self, x)

    def reverse(self):
        r"""reverse(ListPoint self)"""
        return _rm.ListPoint_reverse(self)
    __swig_destroy__ = _rm.delete_ListPoint

# Register ListPoint in _rm:
_rm.ListPoint_swigregister(ListPoint)
class _CymPyDataObj(object):
    r"""Proxy of C++ _CymPyDataObj class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rm.delete__CymPyDataObj
    __hash__ = lambda self: hash(self.__repr__())

    def GetObjType(self):
        r"""GetObjType(_CymPyDataObj self) -> CYMString"""
        return _rm._CymPyDataObj_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""GetValue(_CymPyDataObj self, CYMString PropertyID) -> CYMString"""
        return _rm._CymPyDataObj_GetValue(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue(_CymPyDataObj self, CYMString Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, double Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, int Value, CYMString PropertyID)
        SetValue(_CymPyDataObj self, bool Value, CYMString PropertyID)
        """
        return _rm._CymPyDataObj_SetValue(self, *args)

    def GetUDD(self, KeywordID):
        r"""GetUDD(_CymPyDataObj self, CYMString KeywordID) -> CYMString"""
        return _rm._CymPyDataObj_GetUDD(self, KeywordID)

    def SetUDD(self, *args):
        r"""
        SetUDD(_CymPyDataObj self, CYMString Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, double Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, int Value, CYMString KeywordID)
        SetUDD(_CymPyDataObj self, bool Value, CYMString KeywordID)
        """
        return _rm._CymPyDataObj_SetUDD(self, *args)

# Register _CymPyDataObj in _rm:
_rm._CymPyDataObj_swigregister(_CymPyDataObj)
class Point(object):
    r"""Proxy of C++ Point class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Point self) -> Point"""
        _rm.Point_swiginit(self, _rm.new_Point())
    __swig_destroy__ = _rm.delete_Point

    def __eq__(self, rObj):
        r"""__eq__(Point self, Point rObj) -> bool"""
        return _rm.Point___eq__(self, rObj)

    def __ne__(self, rObj):
        r"""__ne__(Point self, Point rObj) -> bool"""
        return _rm.Point___ne__(self, rObj)

    def cymprint(self):
    	return "(X: " + str(self.X) + ", Y: " + str(self.Y) + ")"

    __str__ = cymprint
    __repr__  = cymprint
    del cymprint

    X = property(_rm.Point_X_get, _rm.Point_X_set, doc=r"""X : double""")
    Y = property(_rm.Point_Y_get, _rm.Point_Y_set, doc=r"""Y : double""")

# Register Point in _rm:
_rm.Point_swigregister(Point)
class SerieList(object):
    r"""Proxy of C++ std::list< Serie > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        r"""iterator(SerieList self) -> SwigPyIterator"""
        return _rm.SerieList_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        r"""__nonzero__(SerieList self) -> bool"""
        return _rm.SerieList___nonzero__(self)

    def __bool__(self):
        r"""__bool__(SerieList self) -> bool"""
        return _rm.SerieList___bool__(self)

    def __len__(self):
        r"""__len__(SerieList self) -> std::list< Serie >::size_type"""
        return _rm.SerieList___len__(self)

    def __getslice__(self, i, j):
        r"""__getslice__(SerieList self, std::list< Serie >::difference_type i, std::list< Serie >::difference_type j) -> SerieList"""
        return _rm.SerieList___getslice__(self, i, j)

    def __setslice__(self, *args):
        r"""
        __setslice__(SerieList self, std::list< Serie >::difference_type i, std::list< Serie >::difference_type j)
        __setslice__(SerieList self, std::list< Serie >::difference_type i, std::list< Serie >::difference_type j, SerieList v)
        """
        return _rm.SerieList___setslice__(self, *args)

    def __delslice__(self, i, j):
        r"""__delslice__(SerieList self, std::list< Serie >::difference_type i, std::list< Serie >::difference_type j)"""
        return _rm.SerieList___delslice__(self, i, j)

    def __delitem__(self, *args):
        r"""
        __delitem__(SerieList self, std::list< Serie >::difference_type i)
        __delitem__(SerieList self, SWIGPY_SLICEOBJECT * slice)
        """
        return _rm.SerieList___delitem__(self, *args)

    def __getitem__(self, *args):
        r"""
        __getitem__(SerieList self, SWIGPY_SLICEOBJECT * slice) -> SerieList
        __getitem__(SerieList self, std::list< Serie >::difference_type i) -> Serie
        """
        return _rm.SerieList___getitem__(self, *args)

    def __setitem__(self, *args):
        r"""
        __setitem__(SerieList self, SWIGPY_SLICEOBJECT * slice, SerieList v)
        __setitem__(SerieList self, SWIGPY_SLICEOBJECT * slice)
        __setitem__(SerieList self, std::list< Serie >::difference_type i, Serie x)
        """
        return _rm.SerieList___setitem__(self, *args)

    def pop(self):
        r"""pop(SerieList self) -> Serie"""
        return _rm.SerieList_pop(self)

    def append(self, x):
        r"""append(SerieList self, Serie x)"""
        return _rm.SerieList_append(self, x)

    def empty(self):
        r"""empty(SerieList self) -> bool"""
        return _rm.SerieList_empty(self)

    def size(self):
        r"""size(SerieList self) -> std::list< Serie >::size_type"""
        return _rm.SerieList_size(self)

    def swap(self, v):
        r"""swap(SerieList self, SerieList v)"""
        return _rm.SerieList_swap(self, v)

    def begin(self):
        r"""begin(SerieList self) -> std::list< Serie >::iterator"""
        return _rm.SerieList_begin(self)

    def end(self):
        r"""end(SerieList self) -> std::list< Serie >::iterator"""
        return _rm.SerieList_end(self)

    def rbegin(self):
        r"""rbegin(SerieList self) -> std::list< Serie >::reverse_iterator"""
        return _rm.SerieList_rbegin(self)

    def rend(self):
        r"""rend(SerieList self) -> std::list< Serie >::reverse_iterator"""
        return _rm.SerieList_rend(self)

    def clear(self):
        r"""clear(SerieList self)"""
        return _rm.SerieList_clear(self)

    def get_allocator(self):
        r"""get_allocator(SerieList self) -> std::list< Serie >::allocator_type"""
        return _rm.SerieList_get_allocator(self)

    def pop_back(self):
        r"""pop_back(SerieList self)"""
        return _rm.SerieList_pop_back(self)

    def erase(self, *args):
        r"""
        erase(SerieList self, std::list< Serie >::iterator pos) -> std::list< Serie >::iterator
        erase(SerieList self, std::list< Serie >::iterator first, std::list< Serie >::iterator last) -> std::list< Serie >::iterator
        """
        return _rm.SerieList_erase(self, *args)

    def __init__(self, *args):
        r"""
        __init__(SerieList self) -> SerieList
        __init__(SerieList self, SerieList other) -> SerieList
        __init__(SerieList self, std::list< Serie >::size_type size) -> SerieList
        __init__(SerieList self, std::list< Serie >::size_type size, Serie value) -> SerieList
        """
        _rm.SerieList_swiginit(self, _rm.new_SerieList(*args))

    def push_back(self, x):
        r"""push_back(SerieList self, Serie x)"""
        return _rm.SerieList_push_back(self, x)

    def front(self):
        r"""front(SerieList self) -> Serie"""
        return _rm.SerieList_front(self)

    def back(self):
        r"""back(SerieList self) -> Serie"""
        return _rm.SerieList_back(self)

    def assign(self, n, x):
        r"""assign(SerieList self, std::list< Serie >::size_type n, Serie x)"""
        return _rm.SerieList_assign(self, n, x)

    def resize(self, *args):
        r"""
        resize(SerieList self, std::list< Serie >::size_type new_size)
        resize(SerieList self, std::list< Serie >::size_type new_size, Serie x)
        """
        return _rm.SerieList_resize(self, *args)

    def insert(self, *args):
        r"""
        insert(SerieList self, std::list< Serie >::iterator pos, Serie x) -> std::list< Serie >::iterator
        insert(SerieList self, std::list< Serie >::iterator pos, std::list< Serie >::size_type n, Serie x)
        """
        return _rm.SerieList_insert(self, *args)

    def pop_front(self):
        r"""pop_front(SerieList self)"""
        return _rm.SerieList_pop_front(self)

    def push_front(self, x):
        r"""push_front(SerieList self, Serie x)"""
        return _rm.SerieList_push_front(self, x)

    def reverse(self):
        r"""reverse(SerieList self)"""
        return _rm.SerieList_reverse(self)
    __swig_destroy__ = _rm.delete_SerieList

# Register SerieList in _rm:
_rm.SerieList_swigregister(SerieList)

def SetGlobalReportMode(ReportMode):
    r"""
    Sets the global report mode.

    Module: cympy.rm

    Args:
       ReportMode -> cympy.enums.ReportModeType

    Return type: 
       cympy.enums.ReportModeType


    """
    return _rm.SetGlobalReportMode(ReportMode)

def Show(*args):
    r"""
    Displays the specified report in CYME.

    Module: cympy.rm

    Remarks:
       - The report of type MSAccess cannot be displayed.
       - When using the XML report type, the report will be opened using the default web browser.
       - When using this function from outside CYME, the report of type CYMESpreadsheet will not be displayed.

    Args:
       ReportName -> str

       Networks -> list of str

       ReportType -> cympy.enums.ReportModeType

       BlendWithCellColor -> boolean (Optional, default: True)

    Return type: 
       None


    """
    return _rm.Show(*args)

def Save(*args):
    r"""
    Saves the specified report to the specified file in the specified format.

    Module: cympy.rm

    Remarks:
       - The spreadsheet report type cannot be saved.

    Args:
       ReportName -> str

       Networks -> list of str

       ReportType -> cympy.enums.ReportModeType

       FileName -> str

       BlendWithCellColor -> boolean (Optional, default: True)

    Return type: 
       None


    """
    return _rm.Save(*args)

def ListReports():
    r"""
    Lists the reports.

    Module: cympy.rm

    Args:
       None

    Return type: 
       list of cympy.rm.Report


    """
    return _rm.ListReports()

def GetReport(ReportName):
    r"""
    Gets a report by name (ex: 'Load Flow - Detailed').

    Module: cympy.rm

    Args:
       ReportName -> str

    Return type: 
       cympy.rm.Report


    """
    return _rm.GetReport(ReportName)

def GetCymeReportsByNetwork(*args):
    r"""
    Gets the reports by network according to a name (ex: 'Load Flow - Detailed').

    Module: cympy.rm

    Args:
       ReportName -> str

       Networks -> list of str (Optional, default: [])

       BlendWithCellColor -> bool (Optional, default: True)

       AllNetworksInSameReport -> bool (Optional, default: False)

       ProjectID -> str (Optional, default: '')

    Return type: 
       list of cympy.rm.CymeReport


    """
    return _rm.GetCymeReportsByNetwork(*args)

def GetCymeDataReports():
    r"""
    Retrieves all CYME data reports in memory.

    Module: cympy.rm

    Args:
       None

    Return type: 
       None


    """
    return _rm.GetCymeDataReports()

def GetChart(ResultKey, Series, XAxisUnitCategory):
    r"""
    Gets a chart.

    Module: cympy.rm

    Args:
       ResultKey -> cympy.rm.ResultKey

       Series -> list of cympy.rm.SeriesKey

       XAxisUnitCategory -> cympy.enums.UnitCategory

    Return type: 
       cympy.rm.Chart


    """
    return _rm.GetChart(ResultKey, Series, XAxisUnitCategory)

def ListResultKeys():
    r"""
    Lists the result keys.

    Module: cympy.rm

    Args:
       None

    Return type: 
       list of cympy.rm.ResultKey


    """
    return _rm.ListResultKeys()
class CustomReport(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.CustomReport_swiginit(self, _rm.new_CustomReport(*args))
    __swig_destroy__ = _rm.delete_CustomReport

    def Show(self):
        r"""
        Displays the custom report.

        Module: cympy.rm

        Args:
           None

        Return type: 
           None


        """
        return _rm.CustomReport_Show(self)

    def Save(self, eReportType, FileName):
        r"""
        Saves the custom report to the specified file in the specified format.

        Module: cympy.rm

        Remarks:
           - The spreadsheet report type cannot be saved.

        Args:
           ReportType -> cympy.enums.ReportModeType

           FileName -> str

        Return type: 
           None


        """
        return _rm.CustomReport_Save(self, eReportType, FileName)

    def AddRow(self, Values):
        return _rm.CustomReport_AddRow(self, Values)
    Title = property(_rm.CustomReport_Title_get, _rm.CustomReport_Title_set)
    Headers = property(_rm.CustomReport_Headers_get, _rm.CustomReport_Headers_set)

# Register CustomReport in _rm:
_rm.CustomReport_swigregister(CustomReport)
class Report(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.Report_swiginit(self, _rm.new_Report())
    __swig_destroy__ = _rm.delete_Report
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def Show(self, *args):
        r"""
        Displays the report.

        Module: cympy.rm

        Remarks:
           - The report of type MSAccess cannot be displayed.
           - When using the XML report type, the report will be opened using the default web browser.
           - When using this function from outside CYME, the report of type CYMESpreadsheet will not be displayed.

        Args:
           Networks -> list of str

           ReportType -> cympy.enums.ReportModeType (Optional, default: cympy.enums.ReportModeType.CYMESpreadsheet)

           BlendWithCellColor -> boolean (Optional, default: True)

        Return type: 
           None


        """
        return _rm.Report_Show(self, *args)

    def Save(self, *args):
        r"""
        Saves the report to the specified file in the specified format.

        Module: cympy.rm

        Remarks:
           - The spreadsheet report type cannot be saved.
           - To keep existing reports you may disable option 'ReplaceExistingFile'.

        Args:
           Networks -> list of str

           ReportType -> cympy.enums.ReportModeType

           FileName -> str

           BlendWithCellColor -> boolean (Optional, default: True)

           ReplaceExistingFile -> boolean (Optional, default: True)

        Return type: 
           None


        """
        return _rm.Report_Save(self, *args)

    def SetProjectID(self, ProjectID):
        r"""
        Sets the current Project ID for the report.

        Module: cympy.rm

        Args:
           ProjectID -> str

        Return type: 
           None


        """
        return _rm.Report_SetProjectID(self, ProjectID)

    def Get(self, *args):
        r"""
        Gets the report for specified networks.

        Module: cympy.rm

        Args:
           Networks -> list of str (Optional, default: [])

           BlendWithCellColor -> bool (Optional, default: true)

        Return type: 
           cympy.rm.CymeReport


        """
        return _rm.Report_Get(self, *args)

    def GetByNetwork(self, *args):
        r"""
        Gets the reports by network for specified networks.

        Remarks:
           - If a report does not support being split by network, it will contain only a single report for all networks.

        Module: cympy.rm

        Args:
           Networks -> list of str (Optional, default: [])

           BlendWithCellColor -> bool (Optional, default: true)

        Return type: 
           cympy.rm.CymeReport


        """
        return _rm.Report_GetByNetwork(self, *args)

    def GetObjType(self):
        r"""
        GetObjType method.

        Module: cympy.rm

        Args:
           None

        Return type: 
           str


        """
        return _rm.Report_GetObjType(self)

    def GetValue(self, PropertyID):
        r"""
        GetValue method.

        Module: cympy.rm

        Args:
           PropertyID -> str

        Return type: 
           str


        """
        return _rm.Report_GetValue(self, PropertyID)

    def SetValue(self, *args):
        r"""
        SetValue method.

        Module: cympy.rm

        Args:
           Value -> str, float, int or bool

           PropertyID -> str

        Return type: 
           void


        """
        return _rm.Report_SetValue(self, *args)

    def Execute(self, PropertyID):
        r"""
        Execute method.

        Module: cympy.rm

        Args:
           PropertyID -> str

        Return type: 
           int


        """
        return _rm.Report_Execute(self, PropertyID)
    Name = property(_rm.Report_Name_get)
    Title = property(_rm.Report_Title_get)
    Category = property(_rm.Report_Category_get)
    StyleSheet = property(_rm.Report_StyleSheet_get)

# Register Report in _rm:
_rm.Report_swigregister(Report)
class ReportCell(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rm.delete_ReportCell
    __hash__ = lambda self: hash(self.__repr__())

    def GetType(self):
        return _rm.ReportCell_GetType(self)
    Format = property(_rm.ReportCell_Format_get, _rm.ReportCell_Format_set)

# Register ReportCell in _rm:
_rm.ReportCell_swigregister(ReportCell)
class IntCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.IntCell_swiginit(self, _rm.new_IntCell(*args))
    __swig_destroy__ = _rm.delete_IntCell

    def GetType(self):
        return _rm.IntCell_GetType(self)
    Value = property(_rm.IntCell_Value_get, _rm.IntCell_Value_set)

# Register IntCell in _rm:
_rm.IntCell_swigregister(IntCell)
class FloatCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.FloatCell_swiginit(self, _rm.new_FloatCell(*args))
    __swig_destroy__ = _rm.delete_FloatCell

    def GetType(self):
        return _rm.FloatCell_GetType(self)
    Value = property(_rm.FloatCell_Value_get, _rm.FloatCell_Value_set)
    Precision = property(_rm.FloatCell_Precision_get, _rm.FloatCell_Precision_set)

# Register FloatCell in _rm:
_rm.FloatCell_swigregister(FloatCell)
class StringCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.StringCell_swiginit(self, _rm.new_StringCell(*args))
    __swig_destroy__ = _rm.delete_StringCell

    def GetType(self):
        return _rm.StringCell_GetType(self)
    Value = property(_rm.StringCell_Value_get, _rm.StringCell_Value_set)

# Register StringCell in _rm:
_rm.StringCell_swigregister(StringCell)
class BooleanCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.BooleanCell_swiginit(self, _rm.new_BooleanCell(*args))
    __swig_destroy__ = _rm.delete_BooleanCell

    def GetType(self):
        return _rm.BooleanCell_GetType(self)
    Value = property(_rm.BooleanCell_Value_get, _rm.BooleanCell_Value_set)

# Register BooleanCell in _rm:
_rm.BooleanCell_swigregister(BooleanCell)
class HyperlinkCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rm.delete_HyperlinkCell

    def GetType(self):
        return _rm.HyperlinkCell_GetType(self)
    Text = property(_rm.HyperlinkCell_Text_get, _rm.HyperlinkCell_Text_set)

# Register HyperlinkCell in _rm:
_rm.HyperlinkCell_swigregister(HyperlinkCell)
class CommandCell(ReportCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.CommandCell_swiginit(self, _rm.new_CommandCell(*args))
    __swig_destroy__ = _rm.delete_CommandCell

    def GetType(self):
        return _rm.CommandCell_GetType(self)
    Text = property(_rm.CommandCell_Text_get, _rm.CommandCell_Text_set)
    Command = property(_rm.CommandCell_Command_get, _rm.CommandCell_Command_set)

# Register CommandCell in _rm:
_rm.CommandCell_swigregister(CommandCell)
class NodeCell(HyperlinkCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.NodeCell_swiginit(self, _rm.new_NodeCell(*args))
    __swig_destroy__ = _rm.delete_NodeCell

    def GetType(self):
        return _rm.NodeCell_GetType(self)
    NodeID = property(_rm.NodeCell_NodeID_get, _rm.NodeCell_NodeID_set)

# Register NodeCell in _rm:
_rm.NodeCell_swigregister(NodeCell)
class DeviceCell(HyperlinkCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.DeviceCell_swiginit(self, _rm.new_DeviceCell(*args))
    __swig_destroy__ = _rm.delete_DeviceCell

    def GetType(self):
        return _rm.DeviceCell_GetType(self)
    DeviceNumber = property(_rm.DeviceCell_DeviceNumber_get, _rm.DeviceCell_DeviceNumber_set)
    DeviceType = property(_rm.DeviceCell_DeviceType_get, _rm.DeviceCell_DeviceType_set)

# Register DeviceCell in _rm:
_rm.DeviceCell_swigregister(DeviceCell)
class SectionCell(HyperlinkCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.SectionCell_swiginit(self, _rm.new_SectionCell(*args))
    __swig_destroy__ = _rm.delete_SectionCell

    def GetType(self):
        return _rm.SectionCell_GetType(self)
    SectionID = property(_rm.SectionCell_SectionID_get, _rm.SectionCell_SectionID_set)

# Register SectionCell in _rm:
_rm.SectionCell_swigregister(SectionCell)
class NetworkCell(HyperlinkCell):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _rm.NetworkCell_swiginit(self, _rm.new_NetworkCell(*args))
    __swig_destroy__ = _rm.delete_NetworkCell

    def GetType(self):
        return _rm.NetworkCell_GetType(self)
    NetworkID = property(_rm.NetworkCell_NetworkID_get, _rm.NetworkCell_NetworkID_set)

# Register NetworkCell in _rm:
_rm.NetworkCell_swigregister(NetworkCell)
class CellFormat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.CellFormat_swiginit(self, _rm.new_CellFormat())
    __swig_destroy__ = _rm.delete_CellFormat
    __hash__ = lambda self: hash(self.__repr__())
    BackColor = property(_rm.CellFormat_BackColor_get, _rm.CellFormat_BackColor_set)
    TextColor = property(_rm.CellFormat_TextColor_get, _rm.CellFormat_TextColor_set)
    Bold = property(_rm.CellFormat_Bold_get, _rm.CellFormat_Bold_set)
    Italic = property(_rm.CellFormat_Italic_get, _rm.CellFormat_Italic_set)
    Underlined = property(_rm.CellFormat_Underlined_get, _rm.CellFormat_Underlined_set)

# Register CellFormat in _rm:
_rm.CellFormat_swigregister(CellFormat)
class Chart(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.Chart_swiginit(self, _rm.new_Chart())
    __swig_destroy__ = _rm.delete_Chart
    __str__ = lambda self: "'" + self.Title + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())

    def Show(self, *args):
        r"""
        Displays the chart in CYME.

        Module: cympy.rm

        Args:
           eChartType -> cympy.enums.ChartType (Optional, default: cympy.enums.ChartType.Unspecified)

        Return type: 
           None


        """
        return _rm.Chart_Show(self, *args)
    Title = property(_rm.Chart_Title_get, _rm.Chart_Title_set)
    SubTitle = property(_rm.Chart_SubTitle_get, _rm.Chart_SubTitle_set)
    Series = property(_rm.Chart_Series_get, _rm.Chart_Series_set)
    TitleX = property(_rm.Chart_TitleX_get, _rm.Chart_TitleX_set)
    TitleY = property(_rm.Chart_TitleY_get, _rm.Chart_TitleY_set)

# Register Chart in _rm:
_rm.Chart_swigregister(Chart)
class Serie(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.Serie_swiginit(self, _rm.new_Serie())
    __swig_destroy__ = _rm.delete_Serie
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_rm.Serie_Name_get, _rm.Serie_Name_set)
    Points = property(_rm.Serie_Points_get, _rm.Serie_Points_set)
    XUnit = property(_rm.Serie_XUnit_get, _rm.Serie_XUnit_set)
    YUnit = property(_rm.Serie_YUnit_get, _rm.Serie_YUnit_set)

# Register Serie in _rm:
_rm.Serie_swigregister(Serie)
class SeriesKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.SeriesKey_swiginit(self, _rm.new_SeriesKey())
    __swig_destroy__ = _rm.delete_SeriesKey
    __str__ = lambda self: "'" + self.Name + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_rm.SeriesKey_Name_get, _rm.SeriesKey_Name_set)
    Group = property(_rm.SeriesKey_Group_get, _rm.SeriesKey_Group_set)
    Suffix = property(_rm.SeriesKey_Suffix_get, _rm.SeriesKey_Suffix_set)

# Register SeriesKey in _rm:
_rm.SeriesKey_swigregister(SeriesKey)
class ResultKey(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.ResultKey_swiginit(self, _rm.new_ResultKey())
    __swig_destroy__ = _rm.delete_ResultKey
    __str__ = lambda self: "'" + self.ItemID + "'"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Group = property(_rm.ResultKey_Group_get, _rm.ResultKey_Group_set)
    Type = property(_rm.ResultKey_Type_get, _rm.ResultKey_Type_set)
    ItemCategory = property(_rm.ResultKey_ItemCategory_get, _rm.ResultKey_ItemCategory_set)
    ItemID = property(_rm.ResultKey_ItemID_get, _rm.ResultKey_ItemID_set)
    Context = property(_rm.ResultKey_Context_get, _rm.ResultKey_Context_set)

# Register ResultKey in _rm:
_rm.ResultKey_swigregister(ResultKey)
class CymeReportRow(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.CymeReportRow_swiginit(self, _rm.new_CymeReportRow())
    __swig_destroy__ = _rm.delete_CymeReportRow
    __str__ = lambda self: "CYME Report Row"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Index = property(_rm.CymeReportRow_Index_get)

    def GetCells(self):
        return _rm.CymeReportRow_GetCells(self)

# Register CymeReportRow in _rm:
_rm.CymeReportRow_swigregister(CymeReportRow)
class CymeReport(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _rm.CymeReport_swiginit(self, _rm.new_CymeReport())
    __swig_destroy__ = _rm.delete_CymeReport
    __str__ = lambda self: "CYME Report '" + self.ReportName + "' (" + self.NetworkName + ")"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Name = property(_rm.CymeReport_Name_get)
    ReportName = property(_rm.CymeReport_ReportName_get)
    NetworkName = property(_rm.CymeReport_NetworkName_get)

    def GetHeaders(self):
        return _rm.CymeReport_GetHeaders(self)

    def GetHeadersGroup(self):
        return _rm.CymeReport_GetHeadersGroup(self)

    def GetRowCount(self):
        return _rm.CymeReport_GetRowCount(self)

    def GetRow(self, nRow):
        return _rm.CymeReport_GetRow(self, nRow)

    def GetAllCells(self, ColumnNames):
        return _rm.CymeReport_GetAllCells(self, ColumnNames)

# Register CymeReport in _rm:
_rm.CymeReport_swigregister(CymeReport)

