# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Simulation module.
Contains functions and classes for working with simulations.
"""

from sys import version_info as _swig_python_version_info
import _sim

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _sim.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _sim.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _sim.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _sim.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err
class LoadValue(object):
    r"""Proxy of C++ LoadValue class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(LoadValue self, double Value1, double Value2) -> LoadValue
        __init__(LoadValue self) -> LoadValue
        """
        _sim.LoadValue_swiginit(self, _sim.new_LoadValue(*args))
    __swig_destroy__ = _sim.delete_LoadValue
    __str__ = lambda self: "Value1: '" + str( self.Value1 ) + "', Value2: '" + str( self.Value2 ) + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    __hash__ = lambda self: hash(self.__repr__())
    Value1 = property(_sim.LoadValue_Value1_get, _sim.LoadValue_Value1_set, doc=r"""Value1 : double""")
    Value2 = property(_sim.LoadValue_Value2_get, _sim.LoadValue_Value2_set, doc=r"""Value2 : double""")

# Register LoadValue in _sim:
_sim.LoadValue_swigregister(LoadValue)
class Meter(object):
    r"""Proxy of C++ Meter class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(Meter self) -> Meter"""
        _sim.Meter_swiginit(self, _sim.new_Meter())
    __swig_destroy__ = _sim.delete_Meter
    __hash__ = lambda self: hash(self.__repr__())
    Connected = property(_sim.Meter_Connected_get, _sim.Meter_Connected_set, doc=r"""Connected : bool""")
    IsTotalDemand = property(_sim.Meter_IsTotalDemand_get, _sim.Meter_IsTotalDemand_set, doc=r"""IsTotalDemand : bool""")
    LoadValueType = property(_sim.Meter_LoadValueType_get, _sim.Meter_LoadValueType_set, doc=r"""LoadValueType : LoadValueType::LoadValueTypeEnum""")
    DemandA = property(_sim.Meter_DemandA_get, _sim.Meter_DemandA_set, doc=r"""DemandA : p.LoadValue""")
    DemandB = property(_sim.Meter_DemandB_get, _sim.Meter_DemandB_set, doc=r"""DemandB : p.LoadValue""")
    DemandC = property(_sim.Meter_DemandC_get, _sim.Meter_DemandC_set, doc=r"""DemandC : p.LoadValue""")
    DemandTotal = property(_sim.Meter_DemandTotal_get, _sim.Meter_DemandTotal_set, doc=r"""DemandTotal : p.LoadValue""")

# Register Meter in _sim:
_sim.Meter_swigregister(Meter)

def IsValidResults(NetworkID, SimulationType):
    r"""
    Indicates if the simulation has valid results.

    Module: cympy.sim

    Args:
       NetworkID -> str

       SimulationType -> cympy.enums.SimulationType

    Return type: 
       bool


    """
    return _sim.IsValidResults(NetworkID, SimulationType)
class Simulation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def GetType(self):
        return _sim.Simulation_GetType(self)

    def GetObjType(self):
        return _sim.Simulation_GetObjType(self)

    def GetValue(self, PropertyID):
        return _sim.Simulation_GetValue(self, PropertyID)

    def Execute(self, PropertyID):
        return _sim.Simulation_Execute(self, PropertyID)

    def SetValue(self, *args):
        return _sim.Simulation_SetValue(self, *args)
    __swig_destroy__ = _sim.delete_Simulation

# Register Simulation in _sim:
_sim.Simulation_swigregister(Simulation)
class LoadFlow(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadFlow_swiginit(self, _sim.new_LoadFlow())
    __swig_destroy__ = _sim.delete_LoadFlow

    def Run(self, *args):
        return _sim.LoadFlow_Run(self, *args)

    def SetLoadingLimit(self, ItemType, LimitCategory, Value):
        return _sim.LoadFlow_SetLoadingLimit(self, ItemType, LimitCategory, Value)

    def GetLoadingLimit(self, ItemType, LimitCategory):
        return _sim.LoadFlow_GetLoadingLimit(self, ItemType, LimitCategory)

# Register LoadFlow in _sim:
_sim.LoadFlow_swigregister(LoadFlow)
class LoadAllocation(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadAllocation_swiginit(self, _sim.new_LoadAllocation())
    __swig_destroy__ = _sim.delete_LoadAllocation

    def Run(self, *args):
        return _sim.LoadAllocation_Run(self, *args)

    def SetDemand(self, *args):
        return _sim.LoadAllocation_SetDemand(self, *args)

# Register LoadAllocation in _sim:
_sim.LoadAllocation_swigregister(LoadAllocation)
class ShortCircuit(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShortCircuit_swiginit(self, _sim.new_ShortCircuit())
    __swig_destroy__ = _sim.delete_ShortCircuit

    def Run(self, *args):
        return _sim.ShortCircuit_Run(self, *args)

# Register ShortCircuit in _sim:
_sim.ShortCircuit_swigregister(ShortCircuit)
class ShortCircuitANSI(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShortCircuitANSI_swiginit(self, _sim.new_ShortCircuitANSI())
    __swig_destroy__ = _sim.delete_ShortCircuitANSI

    def Run(self, *args):
        return _sim.ShortCircuitANSI_Run(self, *args)

# Register ShortCircuitANSI in _sim:
_sim.ShortCircuitANSI_swigregister(ShortCircuitANSI)
class ShortCircuitIEC(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShortCircuitIEC_swiginit(self, _sim.new_ShortCircuitIEC())
    __swig_destroy__ = _sim.delete_ShortCircuitIEC

    def Run(self, *args):
        return _sim.ShortCircuitIEC_Run(self, *args)

# Register ShortCircuitIEC in _sim:
_sim.ShortCircuitIEC_swigregister(ShortCircuitIEC)
class ShortCircuitSeriesFault(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShortCircuitSeriesFault_swiginit(self, _sim.new_ShortCircuitSeriesFault())
    __swig_destroy__ = _sim.delete_ShortCircuitSeriesFault

    def Run(self, *args):
        return _sim.ShortCircuitSeriesFault_Run(self, *args)

# Register ShortCircuitSeriesFault in _sim:
_sim.ShortCircuitSeriesFault_swigregister(ShortCircuitSeriesFault)
class VVO(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.VVO_swiginit(self, _sim.new_VVO())
    __swig_destroy__ = _sim.delete_VVO

    def Run(self):
        return _sim.VVO_Run(self)

# Register VVO in _sim:
_sim.VVO_swigregister(VVO)
class Harmonic(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.Harmonic_swiginit(self, _sim.new_Harmonic())
    __swig_destroy__ = _sim.delete_Harmonic

    def Run(self):
        return _sim.Harmonic_Run(self)

# Register Harmonic in _sim:
_sim.Harmonic_swigregister(Harmonic)
class ProtectiveDeviceAnalysis(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ProtectiveDeviceAnalysis_swiginit(self, _sim.new_ProtectiveDeviceAnalysis())
    __swig_destroy__ = _sim.delete_ProtectiveDeviceAnalysis

    def Run(self, *args):
        return _sim.ProtectiveDeviceAnalysis_Run(self, *args)

    def GetCoordinationResults(self):
        return _sim.ProtectiveDeviceAnalysis_GetCoordinationResults(self)

# Register ProtectiveDeviceAnalysis in _sim:
_sim.ProtectiveDeviceAnalysis_swigregister(ProtectiveDeviceAnalysis)
class RAM(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.RAM_swiginit(self, _sim.new_RAM())
    __swig_destroy__ = _sim.delete_RAM

    def Run(self, *args):
        return _sim.RAM_Run(self, *args)

# Register RAM in _sim:
_sim.RAM_swigregister(RAM)
class LoadingLimit(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadingLimit_swiginit(self, _sim.new_LoadingLimit())
    __swig_destroy__ = _sim.delete_LoadingLimit
    Level = property(_sim.LoadingLimit_Level_get, _sim.LoadingLimit_Level_set)
    Value = property(_sim.LoadingLimit_Value_get, _sim.LoadingLimit_Value_set)

# Register LoadingLimit in _sim:
_sim.LoadingLimit_swigregister(LoadingLimit)
class CAM(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.CAM_swiginit(self, _sim.new_CAM())
    __swig_destroy__ = _sim.delete_CAM

    def Run(self):
        return _sim.CAM_Run(self)

    def AddOutage(self, Outage):
        return _sim.CAM_AddOutage(self, Outage)

    def RemoveOutage(self, Outage):
        return _sim.CAM_RemoveOutage(self, Outage)

    def ListOutages(self):
        return _sim.CAM_ListOutages(self)

    def SetLoadingLimit(self, EquipmentType, StageType, LoadingLimit):
        return _sim.CAM_SetLoadingLimit(self, EquipmentType, StageType, LoadingLimit)

    def GetLoadingLimit(self, EquipmentType, StageType):
        return _sim.CAM_GetLoadingLimit(self, EquipmentType, StageType)

    def GetResults(self):
        return _sim.CAM_GetResults(self)

# Register CAM in _sim:
_sim.CAM_swigregister(CAM)
class CAMNetworkResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.CAMNetworkResult_swiginit(self, _sim.new_CAMNetworkResult())
    __swig_destroy__ = _sim.delete_CAMNetworkResult
    NetworkID = property(_sim.CAMNetworkResult_NetworkID_get)
    SourceEquivalent = property(_sim.CAMNetworkResult_SourceEquivalent_get)
    Capacity = property(_sim.CAMNetworkResult_Capacity_get)
    InitialKVA = property(_sim.CAMNetworkResult_InitialKVA_get)
    FinalKVA = property(_sim.CAMNetworkResult_FinalKVA_get)
    RestoredKW = property(_sim.CAMNetworkResult_RestoredKW_get)
    RestoredCount = property(_sim.CAMNetworkResult_RestoredCount_get)
    FinalCountOut = property(_sim.CAMNetworkResult_FinalCountOut_get)
    FinalKwOut = property(_sim.CAMNetworkResult_FinalKwOut_get)

# Register CAMNetworkResult in _sim:
_sim.CAMNetworkResult_swigregister(CAMNetworkResult)
class OutageLocation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _sim.OutageLocation_swiginit(self, _sim.new_OutageLocation(*args))
    __swig_destroy__ = _sim.delete_OutageLocation
    DeviceNumber = property(_sim.OutageLocation_DeviceNumber_get, _sim.OutageLocation_DeviceNumber_set)
    OutageType = property(_sim.OutageLocation_OutageType_get, _sim.OutageLocation_OutageType_set)

# Register OutageLocation in _sim:
_sim.OutageLocation_swigregister(OutageLocation)
class ContingencyScenarioResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _sim.ContingencyScenarioResult_swiginit(self, _sim.new_ContingencyScenarioResult(*args))
    __swig_destroy__ = _sim.delete_ContingencyScenarioResult

    def GetOutageList(self):
        return _sim.ContingencyScenarioResult_GetOutageList(self)

    def GetSwitchingPlan(self):
        return _sim.ContingencyScenarioResult_GetSwitchingPlan(self)

    def GetRecoveryArea(self):
        return _sim.ContingencyScenarioResult_GetRecoveryArea(self)
    Name = property(_sim.ContingencyScenarioResult_Name_get)
    UnservedCustomersCount = property(_sim.ContingencyScenarioResult_UnservedCustomersCount_get)
    UnservedCustomersKW = property(_sim.ContingencyScenarioResult_UnservedCustomersKW_get)

# Register ContingencyScenarioResult in _sim:
_sim.ContingencyScenarioResult_swigregister(ContingencyScenarioResult)
class ArcFlash(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ArcFlash_swiginit(self, _sim.new_ArcFlash())
    __swig_destroy__ = _sim.delete_ArcFlash

    def Run(self, *args):
        return _sim.ArcFlash_Run(self, *args)

# Register ArcFlash in _sim:
_sim.ArcFlash_swigregister(ArcFlash)
class OPF(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.OPF_swiginit(self, _sim.new_OPF())
    __swig_destroy__ = _sim.delete_OPF

    def Run(self, *args):
        return _sim.OPF_Run(self, *args)

# Register OPF in _sim:
_sim.OPF_swigregister(OPF)
class CapacitorPlacement(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.CapacitorPlacement_swiginit(self, _sim.new_CapacitorPlacement())
    __swig_destroy__ = _sim.delete_CapacitorPlacement

    def Run(self):
        return _sim.CapacitorPlacement_Run(self)

    def GetResults(self):
        return _sim.CapacitorPlacement_GetResults(self)

# Register CapacitorPlacement in _sim:
_sim.CapacitorPlacement_swigregister(CapacitorPlacement)
class CapacitorPlacementInstallation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_CapacitorPlacementInstallation
    SectionID = property(_sim.CapacitorPlacementInstallation_SectionID_get)
    CapacitorFixedPower = property(_sim.CapacitorPlacementInstallation_CapacitorFixedPower_get)
    CapacitorSwitchedPower = property(_sim.CapacitorPlacementInstallation_CapacitorSwitchedPower_get)
    LossReduction = property(_sim.CapacitorPlacementInstallation_LossReduction_get)
    VoltageIncrease = property(_sim.CapacitorPlacementInstallation_VoltageIncrease_get)
    Savings = property(_sim.CapacitorPlacementInstallation_Savings_get)

# Register CapacitorPlacementInstallation in _sim:
_sim.CapacitorPlacementInstallation_swigregister(CapacitorPlacementInstallation)
class CapacitorPlacementResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_CapacitorPlacementResult
    Light = property(_sim.CapacitorPlacementResult_Light_get)
    Normal = property(_sim.CapacitorPlacementResult_Normal_get)
    Peak = property(_sim.CapacitorPlacementResult_Peak_get)

# Register CapacitorPlacementResult in _sim:
_sim.CapacitorPlacementResult_swigregister(CapacitorPlacementResult)
class CapacitorPlacementCondition(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_CapacitorPlacementCondition

    def GetInstallations(self):
        return _sim.CapacitorPlacementCondition_GetInstallations(self)
    TotalFixedCapacitor = property(_sim.CapacitorPlacementCondition_TotalFixedCapacitor_get)
    TotalSwitchedCapacitor = property(_sim.CapacitorPlacementCondition_TotalSwitchedCapacitor_get)
    LossReduction = property(_sim.CapacitorPlacementCondition_LossReduction_get)
    CorrectedPF = property(_sim.CapacitorPlacementCondition_CorrectedPF_get)

# Register CapacitorPlacementCondition in _sim:
_sim.CapacitorPlacementCondition_swigregister(CapacitorPlacementCondition)
class DynamicMotorStart(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DynamicMotorStart_swiginit(self, _sim.new_DynamicMotorStart())
    __swig_destroy__ = _sim.delete_DynamicMotorStart

    def Run(self):
        return _sim.DynamicMotorStart_Run(self)

# Register DynamicMotorStart in _sim:
_sim.DynamicMotorStart_swigregister(DynamicMotorStart)
class LockedRotor(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LockedRotor_swiginit(self, _sim.new_LockedRotor())
    __swig_destroy__ = _sim.delete_LockedRotor

    def Run(self, IncludeUpstreamNetworks=True):
        return _sim.LockedRotor_Run(self, IncludeUpstreamNetworks)

# Register LockedRotor in _sim:
_sim.LockedRotor_swigregister(LockedRotor)
class MaximumStartSize(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.MaximumStartSize_swiginit(self, _sim.new_MaximumStartSize())
    __swig_destroy__ = _sim.delete_MaximumStartSize

    def Run(self):
        return _sim.MaximumStartSize_Run(self)

# Register MaximumStartSize in _sim:
_sim.MaximumStartSize_swigregister(MaximumStartSize)
class EquipmentRatingVerification(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.EquipmentRatingVerification_swiginit(self, _sim.new_EquipmentRatingVerification())
    __swig_destroy__ = _sim.delete_EquipmentRatingVerification

    def Run(self, *args):
        return _sim.EquipmentRatingVerification_Run(self, *args)

# Register EquipmentRatingVerification in _sim:
_sim.EquipmentRatingVerification_swigregister(EquipmentRatingVerification)
class LoadFlowWithProfiles(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadFlowWithProfiles_swiginit(self, _sim.new_LoadFlowWithProfiles())
    __swig_destroy__ = _sim.delete_LoadFlowWithProfiles

    def Run(self, *args):
        return _sim.LoadFlowWithProfiles_Run(self, *args)

    def ActivateShowResults(self, bShowResults):
        return _sim.LoadFlowWithProfiles_ActivateShowResults(self, bShowResults)
    ShowResults = property(_sim.LoadFlowWithProfiles_ShowResults_get, _sim.LoadFlowWithProfiles_ShowResults_set)

# Register LoadFlowWithProfiles in _sim:
_sim.LoadFlowWithProfiles_swigregister(LoadFlowWithProfiles)
class DCArcFlash(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DCArcFlash_swiginit(self, _sim.new_DCArcFlash())
    __swig_destroy__ = _sim.delete_DCArcFlash

    def Run(self):
        return _sim.DCArcFlash_Run(self)

# Register DCArcFlash in _sim:
_sim.DCArcFlash_swigregister(DCArcFlash)
class FaultLocator(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.FaultLocator_swiginit(self, _sim.new_FaultLocator())
    __swig_destroy__ = _sim.delete_FaultLocator

    def Run(self):
        return _sim.FaultLocator_Run(self)

    def GetLocations(self):
        return _sim.FaultLocator_GetLocations(self)

    def GetMonitoredLocations(self, ID, FaultType):
        return _sim.FaultLocator_GetMonitoredLocations(self, ID, FaultType)

# Register FaultLocator in _sim:
_sim.FaultLocator_swigregister(FaultLocator)
class FaultLocatorLocation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_FaultLocatorLocation
    FeederID = property(_sim.FaultLocatorLocation_FeederID_get)
    ID = property(_sim.FaultLocatorLocation_ID_get)
    FaultType = property(_sim.FaultLocatorLocation_FaultType_get)
    Distance = property(_sim.FaultLocatorLocation_Distance_get)

# Register FaultLocatorLocation in _sim:
_sim.FaultLocatorLocation_swigregister(FaultLocatorLocation)
class FaultLocatorMonitoredLocation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_FaultLocatorMonitoredLocation
    MonitoredItemType = property(_sim.FaultLocatorMonitoredLocation_MonitoredItemType_get)
    RecordedType = property(_sim.FaultLocatorMonitoredLocation_RecordedType_get)
    MonitoredID = property(_sim.FaultLocatorMonitoredLocation_MonitoredID_get)
    Value = property(_sim.FaultLocatorMonitoredLocation_Value_get)
    Diff = property(_sim.FaultLocatorMonitoredLocation_Diff_get)

# Register FaultLocatorMonitoredLocation in _sim:
_sim.FaultLocatorMonitoredLocation_swigregister(FaultLocatorMonitoredLocation)
class MinimumFault(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.MinimumFault_swiginit(self, _sim.new_MinimumFault())
    __swig_destroy__ = _sim.delete_MinimumFault

    def Run(self, *args):
        return _sim.MinimumFault_Run(self, *args)

    def GetMinimumFaultZones(self):
        return _sim.MinimumFault_GetMinimumFaultZones(self)

    def GetMinimumFaultNodes(self):
        return _sim.MinimumFault_GetMinimumFaultNodes(self)

# Register MinimumFault in _sim:
_sim.MinimumFault_swigregister(MinimumFault)
class MinimumFaultNode(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_MinimumFaultNode
    NodeID = property(_sim.MinimumFaultNode_NodeID_get)
    NetworkID = property(_sim.MinimumFaultNode_NetworkID_get)
    FaultTypeName = property(_sim.MinimumFaultNode_FaultTypeName_get)
    ProtectiveDeviceSectionID = property(_sim.MinimumFaultNode_ProtectiveDeviceSectionID_get)
    ProtectiveDeviceNumber = property(_sim.MinimumFaultNode_ProtectiveDeviceNumber_get)
    ProtectiveDeviceType = property(_sim.MinimumFaultNode_ProtectiveDeviceType_get)
    BackupProtectiveDeviceSectionID = property(_sim.MinimumFaultNode_BackupProtectiveDeviceSectionID_get)
    BackupProtectiveDeviceNumber = property(_sim.MinimumFaultNode_BackupProtectiveDeviceNumber_get)
    BackupProtectiveDeviceType = property(_sim.MinimumFaultNode_BackupProtectiveDeviceType_get)
    ProtectiveDeviceSettingPhase = property(_sim.MinimumFaultNode_ProtectiveDeviceSettingPhase_get)
    ProtectiveDeviceSettingGround = property(_sim.MinimumFaultNode_ProtectiveDeviceSettingGround_get)
    FaultCurrentSeenByDevicePhase = property(_sim.MinimumFaultNode_FaultCurrentSeenByDevicePhase_get)
    FaultCurrentSeenByDeviceGround = property(_sim.MinimumFaultNode_FaultCurrentSeenByDeviceGround_get)
    FaultCurrentPhase = property(_sim.MinimumFaultNode_FaultCurrentPhase_get)
    FaultCurrentGround = property(_sim.MinimumFaultNode_FaultCurrentGround_get)
    FaultType = property(_sim.MinimumFaultNode_FaultType_get)
    IsProtectedPhase = property(_sim.MinimumFaultNode_IsProtectedPhase_get)
    IsProtectedGround = property(_sim.MinimumFaultNode_IsProtectedGround_get)
    IsMultipleProtection = property(_sim.MinimumFaultNode_IsMultipleProtection_get)
    IsBackupProtected = property(_sim.MinimumFaultNode_IsBackupProtected_get)
    IsException = property(_sim.MinimumFaultNode_IsException_get)

# Register MinimumFaultNode in _sim:
_sim.MinimumFaultNode_swigregister(MinimumFaultNode)
class MinimumFaultZone(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_MinimumFaultZone
    FeederID = property(_sim.MinimumFaultZone_FeederID_get)
    ProtectiveDeviceID = property(_sim.MinimumFaultZone_ProtectiveDeviceID_get)
    ProtectiveDeviceType = property(_sim.MinimumFaultZone_ProtectiveDeviceType_get)
    SwitchingDeviceID = property(_sim.MinimumFaultZone_SwitchingDeviceID_get)
    Bound = property(_sim.MinimumFaultZone_Bound_get)
    CriticalPoint = property(_sim.MinimumFaultZone_CriticalPoint_get)
    FaultTypeName = property(_sim.MinimumFaultZone_FaultTypeName_get)
    BackupProtectiveDeviceSectionID = property(_sim.MinimumFaultZone_BackupProtectiveDeviceSectionID_get)
    BackupProtectiveDeviceNumber = property(_sim.MinimumFaultZone_BackupProtectiveDeviceNumber_get)
    BackupProtectiveDeviceType = property(_sim.MinimumFaultZone_BackupProtectiveDeviceType_get)
    MinimFault = property(_sim.MinimumFaultZone_MinimFault_get)
    ProtectiveDeviceSetting = property(_sim.MinimumFaultZone_ProtectiveDeviceSetting_get)
    MinimFaultWithRatio = property(_sim.MinimumFaultZone_MinimFaultWithRatio_get)
    FromEquipmentType = property(_sim.MinimumFaultZone_FromEquipmentType_get)
    ToEquipmentType = property(_sim.MinimumFaultZone_ToEquipmentType_get)
    WorseCaseEquipmentType = property(_sim.MinimumFaultZone_WorseCaseEquipmentType_get)
    SwitchDevEquipmentType = property(_sim.MinimumFaultZone_SwitchDevEquipmentType_get)
    FromPhase = property(_sim.MinimumFaultZone_FromPhase_get)
    ToPhase = property(_sim.MinimumFaultZone_ToPhase_get)
    WorseCasePhase = property(_sim.MinimumFaultZone_WorseCasePhase_get)
    SwitchDevPhase = property(_sim.MinimumFaultZone_SwitchDevPhase_get)
    FaultType = property(_sim.MinimumFaultZone_FaultType_get)
    IsProtected = property(_sim.MinimumFaultZone_IsProtected_get)
    IsBackupProtected = property(_sim.MinimumFaultZone_IsBackupProtected_get)
    IsException = property(_sim.MinimumFaultZone_IsException_get)

# Register MinimumFaultZone in _sim:
_sim.MinimumFaultZone_swigregister(MinimumFaultZone)
class DistributionStateEstimator(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DistributionStateEstimator_swiginit(self, _sim.new_DistributionStateEstimator())
    __swig_destroy__ = _sim.delete_DistributionStateEstimator

    def Run(self, *args):
        return _sim.DistributionStateEstimator_Run(self, *args)

# Register DistributionStateEstimator in _sim:
_sim.DistributionStateEstimator_swigregister(DistributionStateEstimator)
class ShortCircuitIEC61363(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShortCircuitIEC61363_swiginit(self, _sim.new_ShortCircuitIEC61363())
    __swig_destroy__ = _sim.delete_ShortCircuitIEC61363

    def Run(self, *args):
        return _sim.ShortCircuitIEC61363_Run(self, *args)

# Register ShortCircuitIEC61363 in _sim:
_sim.ShortCircuitIEC61363_swigregister(ShortCircuitIEC61363)
class VoltageSag(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.VoltageSag_swiginit(self, _sim.new_VoltageSag())
    __swig_destroy__ = _sim.delete_VoltageSag

    def Run(self, NodeID):
        return _sim.VoltageSag_Run(self, NodeID)

    def GetLocations(self):
        return _sim.VoltageSag_GetLocations(self)

# Register VoltageSag in _sim:
_sim.VoltageSag_swigregister(VoltageSag)
class VoltageSagLocation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_VoltageSagLocation
    __str__ = lambda self: "(NetworkID: '" + self.NetworkID + "', FaultedItemID: '" + self.FaultedItemID + "', FaultType: '" + str( self.FaultType ) + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    FaultedItemID = property(_sim.VoltageSagLocation_FaultedItemID_get)
    NetworkID = property(_sim.VoltageSagLocation_NetworkID_get)
    DelimiterDeviceNumber = property(_sim.VoltageSagLocation_DelimiterDeviceNumber_get)
    FaultType = property(_sim.VoltageSagLocation_FaultType_get)
    ItemType = property(_sim.VoltageSagLocation_ItemType_get)
    DelimiterDeviceType = property(_sim.VoltageSagLocation_DelimiterDeviceType_get)
    Vmin = property(_sim.VoltageSagLocation_Vmin_get)
    FaultedItemDistance = property(_sim.VoltageSagLocation_FaultedItemDistance_get)
    Frequency = property(_sim.VoltageSagLocation_Frequency_get)
    SagVoltageMin = property(_sim.VoltageSagLocation_SagVoltageMin_get)
    SagVoltageMax = property(_sim.VoltageSagLocation_SagVoltageMax_get)
    SagDuration = property(_sim.VoltageSagLocation_SagDuration_get)
    DelimiterIMax = property(_sim.VoltageSagLocation_DelimiterIMax_get)

# Register VoltageSagLocation in _sim:
_sim.VoltageSagLocation_swigregister(VoltageSagLocation)
class DCShortCircuit(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DCShortCircuit_swiginit(self, _sim.new_DCShortCircuit())
    __swig_destroy__ = _sim.delete_DCShortCircuit

    def Run(self):
        return _sim.DCShortCircuit_Run(self)

# Register DCShortCircuit in _sim:
_sim.DCShortCircuit_swigregister(DCShortCircuit)
class DCLoadFlow(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DCLoadFlow_swiginit(self, _sim.new_DCLoadFlow())
    __swig_destroy__ = _sim.delete_DCLoadFlow

    def Run(self):
        return _sim.DCLoadFlow_Run(self)

# Register DCLoadFlow in _sim:
_sim.DCLoadFlow_swigregister(DCLoadFlow)
class NetworkConfigurationOptimization(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.NetworkConfigurationOptimization_swiginit(self, _sim.new_NetworkConfigurationOptimization())
    __swig_destroy__ = _sim.delete_NetworkConfigurationOptimization

    def Run(self, *args):
        return _sim.NetworkConfigurationOptimization_Run(self, *args)

    def GetSwitchingPlan(self):
        return _sim.NetworkConfigurationOptimization_GetSwitchingPlan(self)

    def GetFeederStatus(self):
        return _sim.NetworkConfigurationOptimization_GetFeederStatus(self)

# Register NetworkConfigurationOptimization in _sim:
_sim.NetworkConfigurationOptimization_swigregister(NetworkConfigurationOptimization)
class NetworkConfigurationOptimizationFeederStatus(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_NetworkConfigurationOptimizationFeederStatus
    NetworkID = property(_sim.NetworkConfigurationOptimizationFeederStatus_NetworkID_get)
    Capacity = property(_sim.NetworkConfigurationOptimizationFeederStatus_Capacity_get)
    InitialKVA = property(_sim.NetworkConfigurationOptimizationFeederStatus_InitialKVA_get)
    FinalKVA = property(_sim.NetworkConfigurationOptimizationFeederStatus_FinalKVA_get)
    InitialLength = property(_sim.NetworkConfigurationOptimizationFeederStatus_InitialLength_get)
    FinalLength = property(_sim.NetworkConfigurationOptimizationFeederStatus_FinalLength_get)
    InitialKWLoss = property(_sim.NetworkConfigurationOptimizationFeederStatus_InitialKWLoss_get)
    FinalKWLoss = property(_sim.NetworkConfigurationOptimizationFeederStatus_FinalKWLoss_get)

# Register NetworkConfigurationOptimizationFeederStatus in _sim:
_sim.NetworkConfigurationOptimizationFeederStatus_swigregister(NetworkConfigurationOptimizationFeederStatus)
class SwitchingOperation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_SwitchingOperation
    DeviceNumber = property(_sim.SwitchingOperation_DeviceNumber_get)
    DeviceType = property(_sim.SwitchingOperation_DeviceType_get)
    Action = property(_sim.SwitchingOperation_Action_get)
    Load = property(_sim.SwitchingOperation_Load_get)
    Customers = property(_sim.SwitchingOperation_Customers_get)
    Stage = property(_sim.SwitchingOperation_Stage_get)
    Reason = property(_sim.SwitchingOperation_Reason_get)
    Losses = property(_sim.SwitchingOperation_Losses_get)
    New = property(_sim.SwitchingOperation_New_get)

# Register SwitchingOperation in _sim:
_sim.SwitchingOperation_swigregister(SwitchingOperation)
class SimultaneousFault(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.SimultaneousFault_swiginit(self, _sim.new_SimultaneousFault())
    __swig_destroy__ = _sim.delete_SimultaneousFault

    def Run(self):
        return _sim.SimultaneousFault_Run(self)

    def AddFault(self, Fault):
        return _sim.SimultaneousFault_AddFault(self, Fault)

    def RemoveFault(self, Index):
        return _sim.SimultaneousFault_RemoveFault(self, Index)

    def GetFaults(self):
        return _sim.SimultaneousFault_GetFaults(self)

# Register SimultaneousFault in _sim:
_sim.SimultaneousFault_swigregister(SimultaneousFault)
class FaultLocation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_FaultLocation

    def GetType(self):
        return _sim.FaultLocation_GetType(self)

# Register FaultLocation in _sim:
_sim.FaultLocation_swigregister(FaultLocation)
class ShuntFault(FaultLocation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ShuntFault_swiginit(self, _sim.new_ShuntFault())
    __swig_destroy__ = _sim.delete_ShuntFault
    __str__ = lambda self: "(FaultType: " + str( self.FaultType ) + ", ItemType: " + str( self.ItemType ) + ", DeviceID: '" + self.DeviceID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    DeviceID = property(_sim.ShuntFault_DeviceID_get, _sim.ShuntFault_DeviceID_set)
    ItemType = property(_sim.ShuntFault_ItemType_get, _sim.ShuntFault_ItemType_set)
    FaultType = property(_sim.ShuntFault_FaultType_get, _sim.ShuntFault_FaultType_set)
    FaultPhase = property(_sim.ShuntFault_FaultPhase_get, _sim.ShuntFault_FaultPhase_set)
    SlidingPosition = property(_sim.ShuntFault_SlidingPosition_get, _sim.ShuntFault_SlidingPosition_set)
    ImpedanceIsOHMS = property(_sim.ShuntFault_ImpedanceIsOHMS_get, _sim.ShuntFault_ImpedanceIsOHMS_set)
    Rf_ohms = property(_sim.ShuntFault_Rf_ohms_get, _sim.ShuntFault_Rf_ohms_set)
    Rg_ohms = property(_sim.ShuntFault_Rg_ohms_get, _sim.ShuntFault_Rg_ohms_set)
    Xf_ohms = property(_sim.ShuntFault_Xf_ohms_get, _sim.ShuntFault_Xf_ohms_set)
    Xg_ohms = property(_sim.ShuntFault_Xg_ohms_get, _sim.ShuntFault_Xg_ohms_set)
    Rf_pu = property(_sim.ShuntFault_Rf_pu_get, _sim.ShuntFault_Rf_pu_set)
    Rg_pu = property(_sim.ShuntFault_Rg_pu_get, _sim.ShuntFault_Rg_pu_set)
    Xf_pu = property(_sim.ShuntFault_Xf_pu_get, _sim.ShuntFault_Xf_pu_set)
    Xg_pu = property(_sim.ShuntFault_Xg_pu_get, _sim.ShuntFault_Xg_pu_set)

    def GetType(self):
        return _sim.ShuntFault_GetType(self)

# Register ShuntFault in _sim:
_sim.ShuntFault_swigregister(ShuntFault)
class SeriesFault(FaultLocation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.SeriesFault_swiginit(self, _sim.new_SeriesFault())
    __swig_destroy__ = _sim.delete_SeriesFault
    __str__ = lambda self: "(FaultType: " + str( self.FaultType ) + ", ItemType: " + str( self.ItemType ) + ", DeviceID: '" + self.DeviceID + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    DeviceID = property(_sim.SeriesFault_DeviceID_get, _sim.SeriesFault_DeviceID_set)
    ItemType = property(_sim.SeriesFault_ItemType_get, _sim.SeriesFault_ItemType_set)
    FaultType = property(_sim.SeriesFault_FaultType_get, _sim.SeriesFault_FaultType_set)
    FaultPhase = property(_sim.SeriesFault_FaultPhase_get, _sim.SeriesFault_FaultPhase_set)
    SlidingPosition = property(_sim.SeriesFault_SlidingPosition_get, _sim.SeriesFault_SlidingPosition_set)
    ImpedanceIsOHMS = property(_sim.SeriesFault_ImpedanceIsOHMS_get, _sim.SeriesFault_ImpedanceIsOHMS_set)
    Ra_ohms = property(_sim.SeriesFault_Ra_ohms_get, _sim.SeriesFault_Ra_ohms_set)
    Rb_ohms = property(_sim.SeriesFault_Rb_ohms_get, _sim.SeriesFault_Rb_ohms_set)
    Rc_ohms = property(_sim.SeriesFault_Rc_ohms_get, _sim.SeriesFault_Rc_ohms_set)
    Xa_ohms = property(_sim.SeriesFault_Xa_ohms_get, _sim.SeriesFault_Xa_ohms_set)
    Xb_ohms = property(_sim.SeriesFault_Xb_ohms_get, _sim.SeriesFault_Xb_ohms_set)
    Xc_ohms = property(_sim.SeriesFault_Xc_ohms_get, _sim.SeriesFault_Xc_ohms_set)
    Ra_pu = property(_sim.SeriesFault_Ra_pu_get, _sim.SeriesFault_Ra_pu_set)
    Rb_pu = property(_sim.SeriesFault_Rb_pu_get, _sim.SeriesFault_Rb_pu_set)
    Rc_pu = property(_sim.SeriesFault_Rc_pu_get, _sim.SeriesFault_Rc_pu_set)
    Xa_pu = property(_sim.SeriesFault_Xa_pu_get, _sim.SeriesFault_Xa_pu_set)
    Xb_pu = property(_sim.SeriesFault_Xb_pu_get, _sim.SeriesFault_Xb_pu_set)
    Xc_pu = property(_sim.SeriesFault_Xc_pu_get, _sim.SeriesFault_Xc_pu_set)

    def GetType(self):
        return _sim.SeriesFault_GetType(self)

# Register SeriesFault in _sim:
_sim.SeriesFault_swigregister(SeriesFault)
class InterCircuitFault(FaultLocation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.InterCircuitFault_swiginit(self, _sim.new_InterCircuitFault())
    __swig_destroy__ = _sim.delete_InterCircuitFault
    __str__ = lambda self: "(FaultType_1: " + str( self.FaultType_1 ) + ", ItemType_1: " + str( self.ItemType_1 ) + ", DeviceID_1: '" + self.DeviceID_1 + "')"
    __repr__ = lambda self: str(self.__class__) + '; ' + self.__str__()
    DeviceID_1 = property(_sim.InterCircuitFault_DeviceID_1_get, _sim.InterCircuitFault_DeviceID_1_set)
    ItemType_1 = property(_sim.InterCircuitFault_ItemType_1_get, _sim.InterCircuitFault_ItemType_1_set)
    FaultType_1 = property(_sim.InterCircuitFault_FaultType_1_get, _sim.InterCircuitFault_FaultType_1_set)
    FaultPhase_1 = property(_sim.InterCircuitFault_FaultPhase_1_get, _sim.InterCircuitFault_FaultPhase_1_set)
    SlidingPosition_1 = property(_sim.InterCircuitFault_SlidingPosition_1_get, _sim.InterCircuitFault_SlidingPosition_1_set)
    DeviceID_2 = property(_sim.InterCircuitFault_DeviceID_2_get, _sim.InterCircuitFault_DeviceID_2_set)
    ItemType_2 = property(_sim.InterCircuitFault_ItemType_2_get, _sim.InterCircuitFault_ItemType_2_set)
    FaultType_2 = property(_sim.InterCircuitFault_FaultType_2_get, _sim.InterCircuitFault_FaultType_2_set)
    FaultPhase_2 = property(_sim.InterCircuitFault_FaultPhase_2_get, _sim.InterCircuitFault_FaultPhase_2_set)
    SlidingPosition_2 = property(_sim.InterCircuitFault_SlidingPosition_2_get, _sim.InterCircuitFault_SlidingPosition_2_set)

    def GetType(self):
        return _sim.InterCircuitFault_GetType(self)

# Register InterCircuitFault in _sim:
_sim.InterCircuitFault_swigregister(InterCircuitFault)
class TCCCoordinationResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_TCCCoordinationResult
    NetworkID = property(_sim.TCCCoordinationResult_NetworkID_get)
    UpstreamDeviceNumber = property(_sim.TCCCoordinationResult_UpstreamDeviceNumber_get)
    UpstreamDeviceType = property(_sim.TCCCoordinationResult_UpstreamDeviceType_get)
    ProtectionType = property(_sim.TCCCoordinationResult_ProtectionType_get)
    UpstreamCurveRating = property(_sim.TCCCoordinationResult_UpstreamCurveRating_get)
    CustomersBetweenDevices = property(_sim.TCCCoordinationResult_CustomersBetweenDevices_get)
    DownstreamDeviceNumber = property(_sim.TCCCoordinationResult_DownstreamDeviceNumber_get)
    DownstreamDeviceType = property(_sim.TCCCoordinationResult_DownstreamDeviceType_get)
    DownstreamCurveRating = property(_sim.TCCCoordinationResult_DownstreamCurveRating_get)
    ProtectionRangeMin_Amp = property(_sim.TCCCoordinationResult_ProtectionRangeMin_Amp_get)
    ProtectionRangeMax_Amp = property(_sim.TCCCoordinationResult_ProtectionRangeMax_Amp_get)
    NonCoordinationPoint_Amp = property(_sim.TCCCoordinationResult_NonCoordinationPoint_Amp_get)
    ErrorCode = property(_sim.TCCCoordinationResult_ErrorCode_get)
    IsCoordination = property(_sim.TCCCoordinationResult_IsCoordination_get)

# Register TCCCoordinationResult in _sim:
_sim.TCCCoordinationResult_swigregister(TCCCoordinationResult)
class InstantaneousProtection(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.InstantaneousProtection_swiginit(self, _sim.new_InstantaneousProtection())
    __swig_destroy__ = _sim.delete_InstantaneousProtection

    def Run(self, *args):
        return _sim.InstantaneousProtection_Run(self, *args)

    def GetResults(self):
        return _sim.InstantaneousProtection_GetResults(self)

# Register InstantaneousProtection in _sim:
_sim.InstantaneousProtection_swigregister(InstantaneousProtection)
class InstantaneousProtectionResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_InstantaneousProtectionResult
    NetworkID = property(_sim.InstantaneousProtectionResult_NetworkID_get)
    ProtectiveDeviceNumber = property(_sim.InstantaneousProtectionResult_ProtectiveDeviceNumber_get)
    AnalysisPoint = property(_sim.InstantaneousProtectionResult_AnalysisPoint_get)
    IsAnalysisPointNode = property(_sim.InstantaneousProtectionResult_IsAnalysisPointNode_get)
    SensitivityIndexPhase = property(_sim.InstantaneousProtectionResult_SensitivityIndexPhase_get)
    InstantPickupPhase_Amp = property(_sim.InstantaneousProtectionResult_InstantPickupPhase_Amp_get)
    MinInstantPickupPhase_Amp = property(_sim.InstantaneousProtectionResult_MinInstantPickupPhase_Amp_get)
    MaxInstantPickupPhase_Amp = property(_sim.InstantaneousProtectionResult_MaxInstantPickupPhase_Amp_get)
    SensitivityIndexGround = property(_sim.InstantaneousProtectionResult_SensitivityIndexGround_get)
    InstantPickupGround_Amp = property(_sim.InstantaneousProtectionResult_InstantPickupGround_Amp_get)
    MinInstantPickupGround_Amp = property(_sim.InstantaneousProtectionResult_MinInstantPickupGround_Amp_get)
    MaxInstantPickupGround_Amp = property(_sim.InstantaneousProtectionResult_MaxInstantPickupGround_Amp_get)

# Register InstantaneousProtectionResult in _sim:
_sim.InstantaneousProtectionResult_swigregister(InstantaneousProtectionResult)
class EnergyConfinement(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.EnergyConfinement_swiginit(self, _sim.new_EnergyConfinement())
    __swig_destroy__ = _sim.delete_EnergyConfinement

    def Run(self, *args):
        return _sim.EnergyConfinement_Run(self, *args)

    def GetSwitchesResultsGrouped(self):
        return _sim.EnergyConfinement_GetSwitchesResultsGrouped(self)

    def GetKevlarResults(self):
        return _sim.EnergyConfinement_GetKevlarResults(self)

    def GetGroundingSetResults(self):
        return _sim.EnergyConfinement_GetGroundingSetResults(self)

# Register EnergyConfinement in _sim:
_sim.EnergyConfinement_swigregister(EnergyConfinement)
class EnergyConfinementResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _sim.delete_EnergyConfinementResult
    NetworkID = property(_sim.EnergyConfinementResult_NetworkID_get)
    Type = property(_sim.EnergyConfinementResult_Type_get)
    Grouping = property(_sim.EnergyConfinementResult_Grouping_get)
    ItemNumber = property(_sim.EnergyConfinementResult_ItemNumber_get)
    FaultType = property(_sim.EnergyConfinementResult_FaultType_get)
    SecurityFactor = property(_sim.EnergyConfinementResult_SecurityFactor_get)
    EnergyLimit = property(_sim.EnergyConfinementResult_EnergyLimit_get)
    ConfinedEnergy = property(_sim.EnergyConfinementResult_ConfinedEnergy_get)
    IsFaultCleared = property(_sim.EnergyConfinementResult_IsFaultCleared_get)
    BackupedFeederID = property(_sim.EnergyConfinementResult_BackupedFeederID_get)
    StrategicBlockHeadID = property(_sim.EnergyConfinementResult_StrategicBlockHeadID_get)

# Register EnergyConfinementResult in _sim:
_sim.EnergyConfinementResult_swigregister(EnergyConfinementResult)
class TransientStability(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.TransientStability_swiginit(self, _sim.new_TransientStability())
    __swig_destroy__ = _sim.delete_TransientStability

    def Run(self):
        return _sim.TransientStability_Run(self)

# Register TransientStability in _sim:
_sim.TransientStability_swigregister(TransientStability)
class IntegrationCapacityAnalysis(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.IntegrationCapacityAnalysis_swiginit(self, _sim.new_IntegrationCapacityAnalysis())
    __swig_destroy__ = _sim.delete_IntegrationCapacityAnalysis

    def Run(self, *args):
        return _sim.IntegrationCapacityAnalysis_Run(self, *args)

# Register IntegrationCapacityAnalysis in _sim:
_sim.IntegrationCapacityAnalysis_swigregister(IntegrationCapacityAnalysis)
class DERImpactEvaluation(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.DERImpactEvaluation_swiginit(self, _sim.new_DERImpactEvaluation())
    __swig_destroy__ = _sim.delete_DERImpactEvaluation

    def Run(self):
        return _sim.DERImpactEvaluation_Run(self)

# Register DERImpactEvaluation in _sim:
_sim.DERImpactEvaluation_swigregister(DERImpactEvaluation)
class LongTermDynamics(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LongTermDynamics_swiginit(self, _sim.new_LongTermDynamics())
    __swig_destroy__ = _sim.delete_LongTermDynamics

    def Run(self, *args):
        return _sim.LongTermDynamics_Run(self, *args)

# Register LongTermDynamics in _sim:
_sim.LongTermDynamics_swigregister(LongTermDynamics)
class EPRIDrive(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.EPRIDrive_swiginit(self, _sim.new_EPRIDrive())
    __swig_destroy__ = _sim.delete_EPRIDrive

    def Run(self, *args):
        return _sim.EPRIDrive_Run(self, *args)

# Register EPRIDrive in _sim:
_sim.EPRIDrive_swigregister(EPRIDrive)
class LoadReliefDispatchable(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadReliefDispatchable_swiginit(self, _sim.new_LoadReliefDispatchable())
    __swig_destroy__ = _sim.delete_LoadReliefDispatchable

    def Run(self, *args):
        return _sim.LoadReliefDispatchable_Run(self, *args)

    def GetLocations(self):
        return _sim.LoadReliefDispatchable_GetLocations(self)

    def Apply(self, NodeID, DeviceType):
        return _sim.LoadReliefDispatchable_Apply(self, NodeID, DeviceType)

# Register LoadReliefDispatchable in _sim:
_sim.LoadReliefDispatchable_swigregister(LoadReliefDispatchable)
class LoadReliefNonDispatchable(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.LoadReliefNonDispatchable_swiginit(self, _sim.new_LoadReliefNonDispatchable())
    __swig_destroy__ = _sim.delete_LoadReliefNonDispatchable

    def Run(self, *args):
        return _sim.LoadReliefNonDispatchable_Run(self, *args)

# Register LoadReliefNonDispatchable in _sim:
_sim.LoadReliefNonDispatchable_swigregister(LoadReliefNonDispatchable)
class NetworkDemandDisaggregation(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.NetworkDemandDisaggregation_swiginit(self, _sim.new_NetworkDemandDisaggregation())
    __swig_destroy__ = _sim.delete_NetworkDemandDisaggregation

    def Run(self, *args):
        return _sim.NetworkDemandDisaggregation_Run(self, *args)

# Register NetworkDemandDisaggregation in _sim:
_sim.NetworkDemandDisaggregation_swigregister(NetworkDemandDisaggregation)
class ThermalCapacity(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ThermalCapacity_swiginit(self, _sim.new_ThermalCapacity())
    __swig_destroy__ = _sim.delete_ThermalCapacity

    def Run(self, *args):
        return _sim.ThermalCapacity_Run(self, *args)

    def ActivateShowResults(self, bShowResults):
        return _sim.ThermalCapacity_ActivateShowResults(self, bShowResults)
    ShowResults = property(_sim.ThermalCapacity_ShowResults_get, _sim.ThermalCapacity_ShowResults_set)

# Register ThermalCapacity in _sim:
_sim.ThermalCapacity_swigregister(ThermalCapacity)
class BTMScenarioAnalysis(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.BTMScenarioAnalysis_swiginit(self, _sim.new_BTMScenarioAnalysis())
    __swig_destroy__ = _sim.delete_BTMScenarioAnalysis

    def Run(self, *args):
        return _sim.BTMScenarioAnalysis_Run(self, *args)

# Register BTMScenarioAnalysis in _sim:
_sim.BTMScenarioAnalysis_swigregister(BTMScenarioAnalysis)
class ProfileAdjustments(Simulation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _sim.ProfileAdjustments_swiginit(self, _sim.new_ProfileAdjustments())
    __swig_destroy__ = _sim.delete_ProfileAdjustments

# Register ProfileAdjustments in _sim:
_sim.ProfileAdjustments_swigregister(ProfileAdjustments)

