# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
CYME Python Utilities module.
Contains utility functions of general use.
"""

from sys import version_info as _swig_python_version_info
import _utils

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SWIG_DOCSTRING_INDENT = _utils.SWIG_DOCSTRING_INDENT

SWIG_DOCSTRING_LIST_MARKER = _utils.SWIG_DOCSTRING_LIST_MARKER

SWIG_DOCSTRING_REMARKS_TITLE = _utils.SWIG_DOCSTRING_REMARKS_TITLE

SWIG_DOCSTRING_ARGUMENTS_TITLE = _utils.SWIG_DOCSTRING_ARGUMENTS_TITLE

import cympy.enums
import cympy.err

def DoesNodeIDExist(NodeID):
    r"""
    Indicates whether the specified node identifier already exists.

    Module: cympy.utils

    Args:
       NodeID -> str

    Return type: 
       bool


    """
    return _utils.DoesNodeIDExist(NodeID)

def DoesSectionIDExist(SectionID):
    r"""
    Indicates whether the specified section identifier already exists.

    Module: cympy.utils

    Args:
       SectionID -> str

    Return type: 
       bool


    """
    return _utils.DoesSectionIDExist(SectionID)

def DoesDeviceNumberExist(DeviceNumber, DeviceType):
    r"""
    Indicates whether the specified device number already exists.

    Module: cympy.utils

    Args:
       DeviceNumber -> str

       DeviceType -> cympy.enums.DeviceType

    Return type: 
       bool


    """
    return _utils.DoesDeviceNumberExist(DeviceNumber, DeviceType)

def GenerateNodeID(*args):
    r"""
    Generates a unique node identifier.

    Module: cympy.utils

    Args:
       NetworkID -> str (Optional, default: '')

    Return type: 
       str


    """
    return _utils.GenerateNodeID(*args)

def GenerateHeadNodeID(*args):
    r"""
    Generates a unique head node identifier.

    Module: cympy.utils

    Args:
       NetworkID -> str (Optional, default: '')

    Return type: 
       str


    """
    return _utils.GenerateHeadNodeID(*args)

def GenerateSectionID(*args):
    r"""
    Generates a unique section identifier.

    Module: cympy.utils

    Args:
       NetworkID -> str (Optional, default: '')

    Return type: 
       str


    """
    return _utils.GenerateSectionID(*args)

def GenerateDeviceNumber(*args):
    r"""
    Generates a unique device number. The generated device number will be unique within the specified device type.

    Module: cympy.utils

    Args:
       DeviceType -> cympy.enums.DeviceType

       DeviceNumber -> str (Optional, default: '')

    Return type: 
       str


    """
    return _utils.GenerateDeviceNumber(*args)

def HasAbnormalCondition(DeviceNumber, DeviceType):
    r"""
    Indicates whether the specified device presents abnormal conditions.

    Module: cympy.utils

    Args:
       DeviceNumber -> str

       DeviceType -> cympy.enums.DeviceType

    Return type: 
       bool


    """
    return _utils.HasAbnormalCondition(DeviceNumber, DeviceType)

def rgb(R, G, B):
    r"""
    Returns the integer representations of the color specified by RGB values. The integer value is calculated using the following logic: bits 0-7 are the blue value, 8-15 the green, and 16-23 the red.

    Module: cympy.utils

    Args:
       R -> cympy.utils.unsigned

       G -> cympy.utils.unsigned

       B -> cympy.utils.unsigned

    Return type: 
       int


    """
    return _utils.rgb(R, G, B)

def xstr(Text):
    r"""
    Returns the regular expression matching exactly the specified text.

    Module: cympy.utils

    Args:
       Text -> str

    Return type: 
       str


    """
    return _utils.xstr(Text)

def ConvertType(EnumValue, ValueType, ConvertType, UseCymeType=False):
    r"""
    Converts an enumeration type to an other type.

    Module: cympy.utils

    Args:
       EnumValue -> int

       ValueType -> cympy.enums.ConversionType

       ConvertType -> cympy.enums.ConversionType

       UseCymeType -> bool (Optional, default: False)

    Return type: 
       int


    """
    return _utils.ConvertType(EnumValue, ValueType, ConvertType, UseCymeType)

def ConvertNameToType(Name, ValueType, ConvertType, UseCymeType=False):
    r"""
    Converts a name to its type.

    Module: cympy.utils

    Args:
       Name -> str

       ValueType -> cympy.enums.ConversionType

       ConvertType -> cympy.enums.ConversionType

       UseCymeType -> bool (Optional, default: False)

    Return type: 
       int


    """
    return _utils.ConvertNameToType(Name, ValueType, ConvertType, UseCymeType)

def ConvertTypeToName(Type, ValueType, ConvertType, UseCymeType=False, FriendlyName=False):
    r"""
    Converts a type to its name.

    Module: cympy.utils

    Args:
       Type -> int

       ValueType -> cympy.enums.ConversionType

       ConvertType -> cympy.enums.ConversionType

       UseCymeType -> bool (Optional, default: False)

       FriendlyName -> bool (Optional, default: False)

    Return type: 
       string


    """
    return _utils.ConvertTypeToName(Type, ValueType, ConvertType, UseCymeType, FriendlyName)

def ConvertFromGPS(Longitude, Latitude):
    r"""
    Converts a Longitude/Latitude coordinate to a X/Y coordinate.

    Module: cympy.utils

    Args:
       Longitude -> float

       Latitude -> float

    Return type: 
       Tuple (int, int)


    """
    return _utils.ConvertFromGPS(Longitude, Latitude)

def ConvertToGPS(X, Y):
    r"""
    Converts a X/Y coordinate to a Longitude/Latitude coordinate.

    Module: cympy.utils

    Args:
       X -> float

       Y -> float

    Return type: 
       Tuple (int, int)


    """
    return _utils.ConvertToGPS(X, Y)

def GetSimulationParametersName(simType):
    r"""
    Gets the parameters name or a given simulation.

    Module: cympy.utils

    Args:
       simType -> cympy.enums.SimulationType

    Return type: 
       str


    """
    return _utils.GetSimulationParametersName(simType)

