WITH base_settings AS (
  SELECT R.S01 AS DEVICE,
    Q.RELAYTYPE AS RELAY,
    T.SETTINGNAME AS ELEMENT,
    DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1) AS SETTING,
    Q.M01 AS MEMO,
    S.REQUESTID,
    TO_NUMBER(
      REGEXP_SUBSTR(T.SETTINGNAME, 'SUBSET (\\d+)', 1, 1, NULL, 1)
    ) AS SUBSET_NUM
  FROM TRELAY R
    INNER JOIN TREQUEST Q ON R.ID = Q.RELAYID
    INNER JOIN TSETTING1 S ON Q.ID = S.REQUESTID
    INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
    AND T.ROWNUMBER = S.ROWNUMBER
  WHERE R.S01 LIKE '${inputCode}%'
    AND R.RELAYTYPE LIKE 'AREVA%'
    AND UPPER(Q.S02) = '${status}'
    AND S.GROUPNAME = 'PARAMETERS'
    AND UPPER(DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1)) <> 'BLOCKED'
    AND (
      T.SETTINGNAME LIKE '%/IDMT1%'
      OR T.SETTINGNAME LIKE '%/DTOC%'
    )
),
enable_settings AS (
  SELECT SE.REQUESTID,
    TO_NUMBER(
      REGEXP_SUBSTR(TE.SETTINGNAME, 'SUBSET (\\d+)', 1, 1, NULL, 1)
    ) AS SUBSET_NUM,
    DBMS_LOB.SUBSTR(SE.SETTING, $ { lobLen }, 1) AS ENABLE_VALUE
  FROM TSETTING1 SE
    INNER JOIN TSETTYPE1 TE ON TE.ROWNUMBER = SE.ROWNUMBER
    INNER JOIN TREQUEST QE ON QE.ID = SE.REQUESTID
    AND TE.RELAYTYPE = QE.RELAYTYPE
    INNER JOIN TRELAY RE ON RE.ID = QE.RELAYID
  WHERE SE.GROUPNAME = 'PARAMETERS'
    AND TE.SETTINGNAME LIKE '%SUBSET _/F<>/ENABLE%'
    AND RE.S01 LIKE '${inputCode}%'
    AND RE.RELAYTYPE LIKE 'AREVA%'
    AND UPPER(QE.S02) = '${status}'
),
sel_tr AS (
  SELECT DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1) AS TR
  FROM TSETTING1 S
    INNER JOIN TREQUEST Q ON Q.ID = S.REQUESTID
    INNER JOIN TRELAY R ON R.ID = Q.RELAYID
    INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
    AND T.ROWNUMBER = S.ROWNUMBER
  WHERE R.S01 LIKE '${inputCode}%'
    AND R.RELAYTYPE LIKE 'SEL%'
    AND S.GROUPNAME = 'L1'
    AND T.SETTINGNAME = 'TR'
    AND UPPER(Q.S02) = '${status}'
),
sel_ctr AS (
  SELECT TO_NUMBER(DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1)) AS CTR
  FROM TSETTING1 S
    INNER JOIN TREQUEST Q ON Q.ID = S.REQUESTID
    INNER JOIN TRELAY R ON R.ID = Q.RELAYID
    INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
    AND T.ROWNUMBER = S.ROWNUMBER
  WHERE R.S01 LIKE '${inputCode}%'
    AND R.RELAYTYPE LIKE 'SEL%'
    AND S.GROUPNAME = '1'
    AND T.SETTINGNAME = 'CTR'
    AND UPPER(Q.S02) = '${status}'
),
sel_candidate_settings AS (
  SELECT R.S01 AS DEVICE,
    Q.RELAYTYPE AS RELAY,
    T.SETTINGNAME AS ELEMENT,
    DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1) AS SETTING_RAW,
    S.GROUPNAME AS GROUPNAME,
    Q.M01 AS MEMO
  FROM TSETTING1 S
    INNER JOIN TREQUEST Q ON Q.ID = S.REQUESTID
    INNER JOIN TRELAY R ON R.ID = Q.RELAYID
    INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
    AND T.ROWNUMBER = S.ROWNUMBER
  WHERE R.S01 LIKE '${inputCode}%'
    AND R.RELAYTYPE LIKE 'SEL%'
    AND UPPER(Q.S02) = '${status}'
)
SELECT B.DEVICE,
  B.RELAY,
  B.ELEMENT,
  B.SETTING,
  B.MEMO
FROM base_settings B
  INNER JOIN enable_settings E ON E.REQUESTID = B.REQUESTID
  AND E.SUBSET_NUM = B.SUBSET_NUM
WHERE UPPER(E.ENABLE_VALUE) = 'YES'
  AND B.ELEMENT NOT LIKE '%/PULS.PROL.IN>%'
  AND B.ELEMENT NOT LIKE '%/HOLD-T. TIN>%'
  AND B.ELEMENT NOT LIKE '%/EVALUATION IN%'
  AND B.ELEMENT NOT LIKE '%/EVAL. IN%'
UNION ALL
SELECT R.S01 AS DEVICE,
  Q.RELAYTYPE AS RELAY,
  T.SETTINGNAME AS ELEMENT,
  DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1) AS SETTING,
  Q.M01 AS MEMO
FROM TRELAY R
  INNER JOIN TREQUEST Q ON R.ID = Q.RELAYID
  INNER JOIN TSETTING1 S ON Q.ID = S.REQUESTID
  INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
  AND T.ROWNUMBER = S.ROWNUMBER
WHERE R.S01 LIKE '${inputCode}%'
  AND R.RELAYTYPE LIKE 'AREVA%'
  AND UPPER(Q.S02) = '${status}'
  AND S.GROUPNAME = 'PARAMETERS'
  AND T.SETTINGNAME LIKE '%/GLOBAL/MAIN/INOM C.T. PRIM.%'
  AND UPPER(DBMS_LOB.SUBSTR(S.SETTING, $ { lobLen }, 1)) <> 'BLOCKED'
UNION ALL
SELECT SCN.DEVICE,
  SCN.RELAY,
  SCN.ELEMENT,
  CASE
    WHEN SCN.ELEMENT NOT LIKE '%C'
    AND SCN.ELEMENT NOT LIKE '%D'
    AND SCN.ELEMENT NOT LIKE '%T'
    AND SCN.ELEMENT NOT LIKE '%OI%'
    AND SCN.GROUPNAME = '1'
    AND UPPER(SCN.SETTING_RAW) <> 'OFF'
    AND REGEXP_LIKE(SCN.SETTING_RAW, '^[+-]?\\d+(\\.\\d+)?$') THEN TO_CHAR(TO_NUMBER(SCN.SETTING_RAW) * CTR.CTR)
    WHEN (
      SCN.ELEMENT LIKE '%OI%'
      OR (
        (
          SCN.ELEMENT LIKE '67%D'
          OR SCN.ELEMENT LIKE '%LT'
        )
        AND SCN.GROUPNAME = '1'
      )
    )
    AND UPPER(SCN.SETTING_RAW) <> 'OFF'
    AND REGEXP_LIKE(SCN.SETTING_RAW, '^[+-]?\\d+(\\.\\d+)?$') THEN TO_CHAR(TO_NUMBER(SCN.SETTING_RAW) / 60)
    ELSE SCN.SETTING_RAW
  END AS SETTING,
  SCN.MEMO
FROM sel_candidate_settings SCN
  CROSS JOIN sel_tr TR
  CROSS JOIN sel_ctr CTR
WHERE (
    SCN.GROUPNAME = '1'
    AND SCN.ELEMENT IN ($ { settingsList })
  )
  OR (
    SCN.GROUPNAME = 'L1'
    AND (
      SCN.ELEMENT LIKE TR.TR
      OR SCN.ELEMENT IN ('51P1TC', '51PTC')
    )
  )
UNION ALL
SELECT R.S01 AS DEVICE,
  Q.RELAYTYPE AS RELAY,
  R.S06 AS VENDOR,
  TO_CHAR(R.S04) AS MODEL,
  Q.M01 AS MEMO
FROM TRELAY R
  INNER JOIN TREQUEST Q ON R.ID = Q.RELAYID
WHERE R.S01 LIKE '${inputCode}%'
  AND UPPER(R.RELAYTYPE) LIKE 'ELECTRO%'
  AND UPPER(Q.S02) = '${status}'