WITH base_settings AS (
  SELECT
    R.S01 AS DEVICE,
    Q.RELAYTYPE AS RELAY,
    T.SETTINGNAME AS ELEMENT,
    DBMS_LOB.SUBSTR(S.SETTING, 4000, 1) AS SETTING,
    Q.M01 AS MEMO,
    S.REQUESTID,
    S.ROWNUMBER,
    TO_NUMBER(
      REGEXP_SUBSTR(T.SETTINGNAME, 'SUBSET (\\d+)', 1, 1, NULL, 1)
    ) AS SUBSET_NUM
  FROM
    TRELAY R
    INNER JOIN TREQUEST Q ON R.ID = Q.RELAYID
    INNER JOIN TSETTING1 S ON Q.ID = S.REQUESTID
    INNER JOIN TSETTYPE1 T ON T.RELAYTYPE = Q.RELAYTYPE
    AND T.ROWNUMBER = S.ROWNUMBER
  WHERE
    R.S01 LIKE 'FCN 25F54%'
    AND R.RELAYTYPE LIKE 'AREVA%'
    AND UPPER(Q.S02) = 'IN SERVICE'
    AND S.GROUPNAME = 'PARAMETERS'
    AND UPPER(DBMS_LOB.SUBSTR(S.SETTING, 4000, 1)) != 'BLOCKED'
    AND (
      T.SETTINGNAME LIKE '%/IDMT1%'
      OR T.SETTINGNAME LIKE '%/DTOC%'
    )
),
enable_settings AS (
  SELECT
    SE.REQUESTID,
    TE.ROWNUMBER,
    SE.SETTING AS ENABLE_VALUE,
    TO_NUMBER(
      REGEXP_SUBSTR(TE.SETTINGNAME, 'SUBSET (\\d+)', 1, 1, NULL, 1)
    ) AS SUBSET_NUM
  FROM
    TSETTING1 SE
    INNER JOIN TSETTYPE1 TE ON TE.ROWNUMBER = SE.ROWNUMBER
    INNER JOIN TREQUEST QE ON QE.ID = SE.REQUESTID
    AND TE.RELAYTYPE = QE.RELAYTYPE
    INNER JOIN TRELAY RE ON RE.ID = QE.RELAYID
  WHERE
    SE.GROUPNAME = 'PARAMETERS'
    AND TE.SETTINGNAME LIKE '%SUBSET _/F<>/ENABLE%'
    AND RE.S01 LIKE 'FCN 25F54%'
    AND RE.RELAYTYPE LIKE 'AREVA%'
    AND UPPER(QE.S02) = 'IN SERVICE'
)
SELECT
  b.DEVICE,
  b.RELAY,
  b.ELEMENT,
  b.SETTING,
  b.MEMO
FROM
  base_settings b
  LEFT JOIN enable_settings e ON e.REQUESTID = b.REQUESTID
  AND e.SUBSET_NUM = b.SUBSET_NUM
WHERE
  UPPER(DBMS_LOB.SUBSTR(e.ENABLE_VALUE, 4000, 1)) = 'YES'
  AND b.ELEMENT NOT LIKE '%/PULS.PROL.IN>%'
  AND b.ELEMENT NOT LIKE '%/HOLD-T. TIN>%'
  AND b.ELEMENT NOT LIKE '%/EVALUATION IN%'
  AND b.ELEMENT NOT LIKE '%/EVAL. IN%'